# Makefile for the cited-research skill repo.
# Generated By: Claude Code (Claude Opus 4.7 (1M context))

.PHONY: check help install install-dev install-no-deps uninstall clean format format-check lint typecheck test test-verbose test-live coverage

PACKAGE_NAME ?= scripts

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/bin/python
endif

$(info venv: $(VENV_DIR))

check: format lint typecheck test coverage  ## Run format, lint, typecheck, test, coverage (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	python3 -m venv $(VENV_DIR)

install: $(PYTHON)  ## Install package
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)  ## Install in editable mode with dev deps
	$(PYTHON) -m pip install -e ".[dev]"

install-no-deps: $(PYTHON)  ## Install in editable mode without dependencies
	$(PYTHON) -m pip install -e . --no-deps

uninstall: $(PYTHON)  ## Uninstall package
	$(PYTHON) -m pip uninstall -y claude-skill-cited-research

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Format code with black
	$(PYTHON) -m black $(PACKAGE_NAME) tests

format-check: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check $(PACKAGE_NAME) tests

lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(PACKAGE_NAME) tests

typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)

test: install-dev  ## Run pytest (skips live-network tests)
	$(PYTHON) -m pytest

test-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

test-live: install-dev  ## Run live-network smoke tests (hits real DuckDuckGo)
	$(PYTHON) -m pytest -m live -v

coverage: install-dev  ## Run pytest with coverage (80% threshold)
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term --cov-fail-under=80
