# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Tests for scripts/fetch_url.py."""

import sys
import urllib.error
from pathlib import Path
from unittest.mock import patch

import pytest

from scripts import _data_paths, fetch_url


@pytest.fixture
def data_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect DATA_ROOT into tmp_path so tests never touch the project."""
    monkeypatch.setattr(_data_paths, "DATA_ROOT", tmp_path)
    return tmp_path


class _FakeResponse:
    """Minimal stand-in for the object urlopen yields as a context manager."""

    def __init__(self, body: bytes, status: int = 200, ctype: str = "text/html"):
        self._body = body
        self.status = status
        self.headers = {"Content-Type": ctype}

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> "_FakeResponse":
        return self

    def __exit__(self, *exc: object) -> None:
        return None


def _raise_http(code: int, body: str):
    """Build a urlopen replacement that raises HTTPError with `body`."""

    class _Err(urllib.error.HTTPError):
        def __init__(self) -> None:
            hdrs: dict = {}
            super().__init__(
                "http://svc/fetch", code, "err", hdrs, None  # type: ignore[arg-type]
            )

        def read(self) -> bytes:  # type: ignore[override]
            return body.encode()

    def _fake(*args: object, **kwargs: object):
        raise _Err()

    return _fake


# ---------------------------------------------------------------------------
# html_to_text


def test_html_to_text_drops_script_and_style() -> None:
    html = "<html><head><style>p{color:red}</style></head><body>"
    html += "<script>var x=1;</script><p>Real prose.</p></body></html>"
    out = fetch_url.html_to_text(html)
    assert "Real prose." in out
    assert "color:red" not in out
    assert "var x" not in out


def test_html_to_text_inlines_absolute_links_only() -> None:
    html = '<p><a href="https://example.com/a">Abs</a> and <a href="/rel">Rel</a></p>'
    out = fetch_url.html_to_text(html)
    assert "(https://example.com/a)" in out
    assert "/rel)" not in out


def test_html_to_text_collapses_blank_lines() -> None:
    out = fetch_url.html_to_text("<div><p>One</p><p></p><p>Two</p></div>")
    assert "\n\n\n" not in out
    assert "One" in out and "Two" in out


def test_html_to_text_falls_back_to_raw_on_parse_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A parser blow-up must not silently produce an empty source file."""

    def _boom(self: object, data: str) -> None:
        raise ValueError("bad markup")

    monkeypatch.setattr(fetch_url._TextExtractor, "feed", _boom)
    raw = "<p>content</p>"
    assert fetch_url.html_to_text(raw) == raw


# ---------------------------------------------------------------------------
# render


def test_render_writes_header_and_extracts_html() -> None:
    out = fetch_url.render("https://x.test/p", "OK", "text/html", "<p>Hi</p>")
    assert out.startswith("# Fetched: https://x.test/p\n# Date: ")
    assert "# Status: OK" in out
    assert "Hi" in out
    assert "<p>" not in out


def test_render_passes_through_plain_text() -> None:
    out = fetch_url.render("https://x.test/t", "OK", "text/plain", "a<b")
    assert "a<b" in out


def test_render_marks_binary_content_failed() -> None:
    out = fetch_url.render("https://x.test/f.pdf", "OK", "application/pdf", "%PDF-1.7")
    assert "# Status: FAILED (binary content-type application/pdf" in out
    assert "%PDF" not in out


def test_render_preserves_existing_failure_status() -> None:
    out = fetch_url.render("https://x.test/p", "FAILED (404: nope)", "", "")
    assert "# Status: FAILED (404: nope)" in out


def test_render_keeps_status_on_one_line() -> None:
    """A multi-line status would spill markup into the header block."""
    out = fetch_url.render("https://x.test/p", "FAILED (404: <html>\n<body>)", "", "")
    header = out.split("\n\n")[0].splitlines()
    assert len(header) == 3
    assert header[2].startswith("# Status: FAILED (404: <html> <body>)")


def test_fetch_collapses_html_error_body_into_status() -> None:
    """Upstream error pages are full HTML documents with newlines."""
    body = "<!DOCTYPE html>\n<html>\n<body>Page not found</body>\n</html>"
    with patch.object(fetch_url.urllib.request, "urlopen", _raise_http(404, body)):
        status, _, _ = fetch_url.fetch("https://x.test/missing")
    assert "\n" not in status
    assert status.startswith("FAILED (404: <!DOCTYPE html> <html>")


# ---------------------------------------------------------------------------
# fetch — error classification


def test_fetch_returns_ok_body() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(b"<p>x</p>")
    ):
        status, ctype, body = fetch_url.fetch("https://x.test/p")
    assert status == "OK"
    assert "text/html" in ctype
    assert body == "<p>x</p>"


def test_fetch_records_upstream_404_as_failed() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(404, "Not Found")
    ):
        status, _, body = fetch_url.fetch("https://x.test/missing")
    assert status.startswith("FAILED (404")
    assert body == ""


def test_fetch_records_service_refusal_as_failed() -> None:
    """403 with a `refused:` body is the service declining one URL."""
    with patch.object(
        fetch_url.urllib.request,
        "urlopen",
        _raise_http(403, "refused: non-public address"),
    ):
        status, _, _ = fetch_url.fetch("https://10.0.0.1/x")
    assert status.startswith("FAILED (403")
    assert "refused" in status


def test_fetch_records_upstream_error_as_failed() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(502, "upstream error: TLS")
    ):
        status, _, _ = fetch_url.fetch("https://x.test/p")
    assert status.startswith("FAILED (502")


def test_fetch_exits_3_on_proxy_policy_denial() -> None:
    """403 without `refused:` is OpenShell's proxy, not the service."""
    with patch.object(
        fetch_url.urllib.request,
        "urlopen",
        _raise_http(403, '{"error":"policy_denied"}'),
    ):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 3


def test_fetch_exits_1_on_bad_request() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(400, "missing url parameter")
    ):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 1


def test_fetch_exits_3_when_service_offline() -> None:
    def _down(*args: object, **kwargs: object):
        raise urllib.error.URLError("connection refused")

    with patch.object(fetch_url.urllib.request, "urlopen", _down):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 3


def test_fetch_percent_encodes_the_url() -> None:
    """An unencoded `?` or `&` would truncate the service's own query string."""
    seen: list[str] = []

    def _capture(url: str, *a: object, **k: object) -> _FakeResponse:
        seen.append(url)
        return _FakeResponse(b"ok", ctype="text/plain")

    with patch.object(fetch_url.urllib.request, "urlopen", _capture):
        fetch_url.fetch("https://x.test/s?q=1&r=2")
    assert "q%3D1%26r%3D2" in seen[0]
    assert seen[0].count("?") == 1


# ---------------------------------------------------------------------------
# check_service


def test_check_service_ok() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(b"", 200)
    ):
        assert fetch_url.check_service() == 0


def test_check_service_offline_returns_3() -> None:
    def _down(*args: object, **kwargs: object):
        raise urllib.error.URLError("refused")

    with patch.object(fetch_url.urllib.request, "urlopen", _down):
        assert fetch_url.check_service() == 3


# ---------------------------------------------------------------------------
# main


def test_main_writes_fetched_file(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    argv = ["fetch_url", "topic", "fetched/p.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request,
            "urlopen",
            lambda *a, **k: _FakeResponse(b"<p>Data</p>"),
        ):
            fetch_url.main()
    written = (data_root / "topic" / "fetched" / "p.md").read_text()
    assert "# Fetched: https://x.test/p" in written
    assert "Data" in written


def test_main_requires_bootstrapped_slug_root(data_root: Path) -> None:
    argv = ["fetch_url", "missing", "fetched/p.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 1


def test_main_rejects_slug_escape(data_root: Path) -> None:
    argv = ["fetch_url", "topic", "../escape.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 1


# ---------------------------------------------------------------------------
# live


@pytest.mark.live
def test_live_fetch_service_health() -> None:
    """Manual sanity check — requires the host fetch service running."""
    assert fetch_url.check_service() == 0


# ---------------------------------------------------------------------------
# 403 disambiguation — three sources, opposite handling


def test_upstream_403_is_recorded_not_fatal() -> None:
    """Bot-protection 403s are routine; they must not abort the run.

    Regression: an upstream Cloudflare block was misread as a proxy policy
    denial and exited 3, killing a batch mid-fetch.
    """
    body = "<html><head><title>403 Forbidden</title></head><body>Denied</body></html>"
    with patch.object(fetch_url.urllib.request, "urlopen", _raise_http(403, body)):
        status, _, _ = fetch_url.fetch("https://blocked.test/p")
    assert status.startswith("FAILED (403")


def test_proxy_denial_detected_by_marker() -> None:
    assert fetch_url.is_proxy_denial(403, '{"error":"policy_denied"}')
    assert fetch_url.is_proxy_denial(403, "GET x not permitted by policy")


def test_non_proxy_403_bodies_are_not_denials() -> None:
    assert not fetch_url.is_proxy_denial(403, "refused: non-public address")
    assert not fetch_url.is_proxy_denial(403, "<html>403 Forbidden</html>")
    assert not fetch_url.is_proxy_denial(404, "policy_denied")


# ---------------------------------------------------------------------------
# Encyclopedia reference mining — deterministic, not model-driven


def test_is_encyclopedia_matches_any_language_subdomain() -> None:
    assert fetch_url.is_encyclopedia("https://en.wikipedia.org/wiki/X")
    assert fetch_url.is_encyclopedia("https://fr.wikipedia.org/wiki/X")
    assert fetch_url.is_encyclopedia("https://grokipedia.com/page/X")
    assert not fetch_url.is_encyclopedia("https://www.irs.gov/pub")
    assert not fetch_url.is_encyclopedia("https://notwikipedia.org.evil.com/x")


def test_extracts_mediawiki_external_links_only() -> None:
    """MediaWiki marks citations with class=external; internal links are noise."""
    html = """
    <a href="/wiki/Internal">internal</a>
    <a href="https://en.wikipedia.org/wiki/Other">same host</a>
    <a class="external text" href="https://www.irs.gov/pub/p527">ref 1</a>
    <a class="external autonumber" href="https://eur-lex.europa.eu/x">ref 2</a>
    <a href="https://example.com/unmarked">unmarked</a>
    """
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://www.irs.gov/pub/p527", "https://eur-lex.europa.eu/x"]


def test_falls_back_to_cross_host_links_when_unmarked() -> None:
    """Grokipedia is not MediaWiki and has no `external` class marker."""
    html = '<a href="https://www.oecd.org/report">r</a><a href="/rel">x</a>'
    refs = fetch_url.extract_reference_urls(html, "https://grokipedia.com/page/X")
    assert refs == ["https://www.oecd.org/report"]


def test_filters_infrastructure_hosts() -> None:
    html = """
    <a class="external" href="https://commons.wikimedia.org/x">commons</a>
    <a class="external" href="https://www.wikidata.org/y">wikidata</a>
    <a class="external" href="https://creativecommons.org/licenses/">cc</a>
    <a class="external" href="https://www.bde.es/report">real source</a>
    """
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://www.bde.es/report"]


def test_reference_urls_are_deduplicated_in_order() -> None:
    html = (
        '<a class="external" href="https://a.test/1">a</a>'
        '<a class="external" href="https://b.test/2">b</a>'
        '<a class="external" href="https://a.test/1">a again</a>'
    )
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://a.test/1", "https://b.test/2"]


def test_malformed_markup_yields_no_refs_rather_than_raising(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _boom(self: object, data: str) -> None:
        raise ValueError("bad markup")

    monkeypatch.setattr(fetch_url._RefExtractor, "feed", _boom)
    assert fetch_url.extract_reference_urls("<a>", "https://en.wikipedia.org/x") == []


def test_main_writes_refs_sidecar_for_encyclopedia(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    html = b'<p>Text</p><a class="external" href="https://www.irs.gov/p527">ref</a>'
    argv = ["fetch_url", "topic", "fetched/wiki.md", "https://en.wikipedia.org/wiki/X"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(html)
        ):
            fetch_url.main()
    sidecar = data_root / "topic" / "fetched" / "wiki.md.refs"
    assert sidecar.read_text().splitlines() == ["https://www.irs.gov/p527"]


def test_main_writes_no_sidecar_for_ordinary_pages(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    html = b'<a href="https://elsewhere.test/x">link</a>'
    argv = ["fetch_url", "topic", "fetched/gov.md", "https://www.irs.gov/pub/p527"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(html)
        ):
            fetch_url.main()
    assert not (data_root / "topic" / "fetched" / "gov.md.refs").exists()
