# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for scripts/multi_search.py."""

import io
import json
import sys
from contextlib import redirect_stdout
from unittest.mock import MagicMock, patch

import pytest

from scripts import multi_search


@pytest.fixture(autouse=True)
def no_backoff_sleep(monkeypatch):
    """Make retry backoff instant.

    Every failure path now retries with real sleeps, which would otherwise
    add seconds per failing-wave test for no coverage.
    """
    monkeypatch.setattr(multi_search, "_sleep_backoff", lambda attempt: None)


# ---------------------------------------------------------------------------
# deduplicate()
# ---------------------------------------------------------------------------


class TestDeduplicate:
    def test_empty_input_returns_empty(self):
        assert multi_search.deduplicate([]) == []

    def test_keeps_first_occurrence_of_duplicate_url(self):
        results = [
            {
                "url": "https://a.example",
                "title": "first",
                "snippet": "",
                "engine": "ddg",
            },
            {
                "url": "https://a.example",
                "title": "second",
                "snippet": "",
                "engine": "ddg",
            },
        ]
        deduped = multi_search.deduplicate(results)
        assert len(deduped) == 1
        assert deduped[0]["title"] == "first"

    def test_preserves_order(self):
        results = [
            {"url": "https://a.example", "title": "a", "snippet": "", "engine": "ddg"},
            {"url": "https://b.example", "title": "b", "snippet": "", "engine": "ddg"},
            {"url": "https://c.example", "title": "c", "snippet": "", "engine": "ddg"},
        ]
        deduped = multi_search.deduplicate(results)
        assert [r["url"] for r in deduped] == [
            "https://a.example",
            "https://b.example",
            "https://c.example",
        ]

    def test_drops_entries_with_empty_url(self):
        results = [
            {"url": "", "title": "no url", "snippet": "", "engine": "ddg"},
            {"url": "https://a.example", "title": "ok", "snippet": "", "engine": "ddg"},
        ]
        deduped = multi_search.deduplicate(results)
        assert len(deduped) == 1
        assert deduped[0]["url"] == "https://a.example"


# ---------------------------------------------------------------------------
# search_ddg() — DDGS mocked
# ---------------------------------------------------------------------------


class TestSearchDdg:
    """search_ddg now runs two disjoint waves and returns a coverage payload."""

    def test_two_waves_both_contribute(self):
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = [
            [{"href": "https://a.example", "title": "A", "body": "Body A"}],
            [{"href": "https://b.example", "title": "B", "body": "Body B"}],
        ]
        with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
            payload = multi_search.search_ddg("q", limit=2, backends="e1,e2")

        assert [r["url"] for r in payload["results"]] == [
            "https://a.example",
            "https://b.example",
        ]
        assert payload["results"][0]["wave"] == "A"
        assert payload["results"][1]["wave"] == "B"
        assert payload["coverage"]["independent_samples"] == 2
        assert payload["coverage"]["single_wave"] is False

    def test_records_candidate_backends_not_a_single_engine(self):
        """ddgs cannot say which backend answered; the record must not claim one."""
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = [
            [{"href": "https://a.example", "title": "A", "body": "B"}],
            [],
        ]
        with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
            payload = multi_search.search_ddg("q", limit=1, backends="brave,bing")

        assert payload["results"][0]["backends"] == "brave"
        assert "engine" not in payload["results"][0]

    def test_one_wave_failing_flags_single_wave(self, capsys):
        def _side_effect(*a, **k):
            if _side_effect.calls == 0:
                _side_effect.calls += 1
                return [{"href": "https://a.example", "title": "A", "body": "B"}]
            raise RuntimeError("blocked")

        _side_effect.calls = 0
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = _side_effect
        with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
            payload = multi_search.search_ddg("q", limit=1, backends="e1,e2")

        assert payload["coverage"]["single_wave"] is True
        assert payload["coverage"]["independent_samples"] == 1
        assert payload["coverage"]["waves_ok"] == ["A"]
        assert "wave B" in capsys.readouterr().err

    def test_empty_wave_counts_as_failed_not_ok(self):
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = [[], []]
        with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
            payload = multi_search.search_ddg("q", limit=1, backends="e1,e2")

        assert payload["coverage"]["independent_samples"] == 0
        assert len(payload["coverage"]["waves_failed"]) == 2

    def test_handles_missing_fields(self):
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = [[{}], []]
        with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
            payload = multi_search.search_ddg("anything", limit=1, backends="e1,e2")

        assert payload["results"][0]["url"] == ""
        assert payload["results"][0]["title"] == ""
        assert payload["results"][0]["snippet"] == ""

    def test_missing_dependency_exits_with_error(self, capsys):
        with patch.dict("sys.modules", {"ddgs": None}):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.search_ddg("anything", limit=1)
        assert excinfo.value.code == 1
        assert "ddgs not installed" in capsys.readouterr().err


class TestSplitWaves:
    def test_interleaves_rather_than_halving(self):
        """Contiguous halves can put every working engine in one wave."""
        a, b = multi_search.split_waves("e1,e2,e3,e4,e5,e6")
        assert a == ["e1", "e3", "e5"]
        assert b == ["e2", "e4", "e6"]

    def test_single_backend_leaves_second_wave_empty(self):
        a, b = multi_search.split_waves("only")
        assert a == ["only"]
        assert b == []

    def test_ignores_blank_entries(self):
        a, b = multi_search.split_waves("e1, ,e2")
        assert a + b == ["e1", "e2"]

    def test_default_backends_split_into_two_usable_waves(self):
        a, b = multi_search.split_waves(",".join(multi_search.default_backends()))
        assert len(a) >= 2 and len(b) >= 2
        assert not set(a) & set(b), "waves must be disjoint"


# ---------------------------------------------------------------------------
# main() — argparse + JSON contract
# ---------------------------------------------------------------------------


class TestMain:
    def _run_main(self, argv: list[str]) -> str:
        buf = io.StringIO()
        with patch.object(sys, "argv", ["multi_search", *argv]):
            with redirect_stdout(buf):
                multi_search.main()
        return buf.getvalue()

    def test_unknown_engine_exits_nonzero(self, capsys):
        with patch.object(
            sys, "argv", ["multi_search", "--query", "x", "--engines", "bing"]
        ):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.main()
        assert excinfo.value.code == 1
        err = capsys.readouterr().err
        assert "unknown engine" in err
        assert "bing" in err

    def test_missing_query_arg_errors(self):
        with patch.object(sys, "argv", ["multi_search"]):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.main()
        # argparse exits with 2 on missing required args
        assert excinfo.value.code == 2

    def test_outputs_dedup_json(self):
        payload = {
            "results": [
                {"url": "https://a.example", "title": "a", "snippet": "", "wave": "A"},
                {
                    "url": "https://a.example",
                    "title": "dup",
                    "snippet": "",
                    "wave": "B",
                },
            ],
            "coverage": {"single_wave": False, "waves_ok": ["A", "B"]},
        }
        with patch.object(
            multi_search, "ENGINE_FUNCTIONS", {"ddg": lambda q, limit, **kw: payload}
        ):
            output = self._run_main(
                ["--query", "x", "--engines", "ddg", "--limit", "5"]
            )

        parsed = json.loads(output)
        assert len(parsed["results"]) == 1
        assert parsed["results"][0]["url"] == "https://a.example"
        assert parsed["results"][0]["title"] == "a"
        assert parsed["coverage"]["waves_ok"] == ["A", "B"]

    def test_coverage_travels_in_the_payload_not_only_stderr(self):
        """A caller must not be able to overlook single-wave coverage."""
        payload = {
            "results": [
                {"url": "https://a.example", "title": "a", "snippet": "", "wave": "A"}
            ],
            "coverage": {
                "single_wave": True,
                "waves_ok": ["A"],
                "wave_a_backends": "e1",
                "wave_b_backends": "e2",
            },
        }
        with patch.object(
            multi_search, "ENGINE_FUNCTIONS", {"ddg": lambda q, limit, **kw: payload}
        ):
            output = self._run_main(["--query", "x"])

        assert json.loads(output)["coverage"]["single_wave"] is True

    def test_empty_results_exit_nonzero(self, capsys):
        payload = {"results": [], "coverage": {"single_wave": False, "waves_ok": []}}
        with patch.object(
            multi_search, "ENGINE_FUNCTIONS", {"ddg": lambda q, limit, **kw: payload}
        ):
            with pytest.raises(SystemExit) as excinfo:
                self._run_main(["--query", "x"])
        assert excinfo.value.code == 1
        assert "no results from any wave" in capsys.readouterr().err

    def test_total_engine_failure_exits_nonzero(self, capsys):
        """An empty array on exit 0 would read as 'ran fine, found nothing'.

        The coordinator would then proceed on single-engine results without
        noticing — the exact bias this script exists to reduce.
        """

        def failing(_query, _limit, **_kw):
            raise RuntimeError("network down")

        with patch.object(multi_search, "ENGINE_FUNCTIONS", {"ddg": failing}):
            with pytest.raises(SystemExit) as excinfo:
                self._run_main(["--query", "x"])

        assert excinfo.value.code == 1
        err = capsys.readouterr().err
        assert "ddg search failed" in err
        assert "Search is unavailable" in err

    def test_partial_engine_failure_still_succeeds(self, capsys):
        """One working engine is a usable result, not a failed run."""

        def failing(_query, _limit, **_kw):
            raise RuntimeError("network down")

        def working(_query, _limit, **_kw):
            return {
                "results": [
                    {
                        "url": "https://a.example",
                        "title": "a",
                        "snippet": "",
                        "wave": "A",
                    }
                ],
                "coverage": {"single_wave": False, "waves_ok": ["A", "B"]},
            }

        engines = {"ddg": failing, "other": working}
        with patch.object(multi_search, "ENGINE_FUNCTIONS", engines):
            with patch.object(multi_search, "SUPPORTED_ENGINES", {"ddg", "other"}):
                output = self._run_main(["--query", "x", "--engines", "ddg,other"])

        assert len(json.loads(output)["results"]) == 1
        assert "ddg search failed" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# Live smoke test — opt-in (`make test-live`)
# ---------------------------------------------------------------------------


@pytest.mark.live
def test_live_ddg_returns_results():
    """Sanity check that the DDGS shape we depend on is unchanged."""
    results = multi_search.search_ddg("python programming language", limit=3)
    assert len(results) >= 1
    first = results[0]
    assert first["url"].startswith("http")
    assert first["engine"] == "ddg"
    assert isinstance(first["title"], str)
    assert isinstance(first["snippet"], str)


def test_search_ddg_passes_one_wave_per_call():
    """Each wave is a separate call — that is what makes the samples independent."""
    fake_ddgs = MagicMock()
    fake_ddgs.__enter__.return_value.text.return_value = []
    with patch.dict("sys.modules", {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)}):
        multi_search.search_ddg("q", limit=5, backends="duckduckgo,brave")
    calls = fake_ddgs.__enter__.return_value.text.call_args_list
    # Both waves are queried, and never in one combined call. Count is not
    # asserted: an empty result is retried, so a dead engine is called more
    # than once per wave.
    backends = [c.kwargs["backend"] for c in calls]
    assert set(backends) == {"duckduckgo", "brave"}, "both waves must be queried"
    assert backends[0] == "duckduckgo", "wave A runs first"
    assert "duckduckgo,brave" not in backends, "waves must not be combined"
    assert calls[0].kwargs["max_results"] == 5


def test_default_backends_are_multiple_engines():
    """A single-engine default would silently reintroduce the bias."""
    assert len(multi_search.default_backends()) >= 3
    assert "auto" not in multi_search.default_backends()


# ---------------------------------------------------------------------------
# run_health() — per-backend probe


def _registry(*names):
    """Patch ddgs.engines so text_backends() returns exactly `names`."""
    fake = MagicMock()
    fake.ENGINES = {"text": {n: object() for n in names}}
    return {"ddgs.engines": fake}


class TestRunHealth:
    def test_distinct_backends_are_alive(self, capsys):
        """Each backend returning its own URLs means isolation is real."""

        def _per_backend(*a, **k):
            return [{"href": f"https://{k['backend']}.example"}]

        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = _per_backend
        mods = {"ddgs": MagicMock(DDGS=lambda: fake_ddgs), **_registry("alpha", "beta")}
        with patch.dict("sys.modules", mods):
            code = multi_search.run_health()
        out = capsys.readouterr().out
        assert code == 0
        assert "suggested --backends" in out
        assert "alpha" in out and "beta" in out

    def test_backend_matching_sentinel_is_flagged_not_counted_alive(self, capsys):
        """A backend echoing the auto-selection pool is a false positive.

        Regression: an unregistered `bing` passed the old probe because ddgs
        silently answered it with the full auto pool.
        """
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.return_value = [{"href": "https://same"}]
        mods = {"ddgs": MagicMock(DDGS=lambda: fake_ddgs), **_registry("alpha", "beta")}
        with patch.dict("sys.modules", mods):
            code = multi_search.run_health()
        captured = capsys.readouterr()
        assert code == 1, "no isolated backend means no two waves"
        assert "FALLBACK" in captured.out
        assert "not isolated" in captured.err

    def test_fewer_than_two_alive_returns_one(self, capsys):
        """Two waves cannot be formed from one engine — that must be an error."""

        def _one_only(*a, **k):
            if k.get("backend") == "duckduckgo":
                return [{"href": "https://a"}]
            raise RuntimeError("blocked")

        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.side_effect = _one_only
        mods = {
            "ddgs": MagicMock(DDGS=lambda: fake_ddgs),
            **_registry("duckduckgo", "brave"),
        }
        with patch.dict("sys.modules", mods):
            code = multi_search.run_health()
        assert code == 1
        assert "two independent waves" in capsys.readouterr().err

    def test_empty_result_counts_as_dead_and_says_why(self, capsys):
        """An engine that answers with nothing is dead, and the reason shows."""
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.return_value = []
        mods = {"ddgs": MagicMock(DDGS=lambda: fake_ddgs), **_registry("alpha", "beta")}
        with patch.dict("sys.modules", mods):
            code = multi_search.run_health()
        assert code == 1
        out = capsys.readouterr().out
        assert "alpha        FAIL" in out
        assert "no results" in out
        assert "alive: 0/2" in out

    def test_missing_dependency_returns_one(self, capsys):
        with patch.dict("sys.modules", {"ddgs": None}):
            code = multi_search.run_health()
        assert code == 1
        assert "ddgs not installed" in capsys.readouterr().err

    def test_health_flag_short_circuits_query_requirement(self):
        with patch.object(multi_search, "run_health", lambda: 0):
            with patch.object(sys, "argv", ["multi_search", "--health"]):
                with pytest.raises(SystemExit) as excinfo:
                    multi_search.main()
        assert excinfo.value.code == 0

    def test_query_required_without_health(self):
        with patch.object(sys, "argv", ["multi_search"]):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.main()
        assert excinfo.value.code == 2


class TestWaveContribution:
    def test_counts_unique_urls_per_wave(self):
        results = [
            {"url": "https://a", "wave": "A"},
            {"url": "https://b", "wave": "A"},
            {"url": "https://c", "wave": "B"},
        ]
        assert multi_search.wave_contribution(results) == {"A": 2, "B": 1}

    def test_wave_adding_nothing_is_absent_from_counts(self):
        """A wave whose results all dedup away broadened nothing."""
        deduped = [{"url": "https://a", "wave": "A"}]
        assert multi_search.wave_contribution(deduped) == {"A": 1}

    def test_main_flags_complete_overlap_between_healthy_waves(self, capsys):
        payload = {
            "results": [
                {"url": "https://a", "title": "a", "snippet": "", "wave": "A"},
                {"url": "https://a", "title": "dup", "snippet": "", "wave": "B"},
            ],
            "coverage": {
                "single_wave": False,
                "waves_ok": ["A", "B"],
                "returned_by_wave": {"A": 1, "B": 1},
            },
        }
        with patch.object(
            multi_search, "ENGINE_FUNCTIONS", {"ddg": lambda q, limit, **kw: payload}
        ):
            buf = io.StringIO()
            with patch.object(sys, "argv", ["multi_search", "--query", "x"]):
                with redirect_stdout(buf):
                    multi_search.main()
        parsed = json.loads(buf.getvalue())
        assert parsed["coverage"]["unique_by_wave"] == {"A": 1}
        assert parsed["coverage"]["waves_adding_unique"] == ["A"]
        assert "overlapped completely" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# Backend registry — read from ddgs, never hardcoded


class TestBackendRegistry:
    def test_text_backends_come_from_the_library(self):
        fake = MagicMock()
        fake.ENGINES = {"text": {"alpha": 1, "beta": 2}, "news": {"gamma": 3}}
        with patch.dict("sys.modules", {"ddgs.engines": fake}):
            assert multi_search.text_backends() == ["alpha", "beta"]

    def test_text_backends_empty_when_ddgs_absent(self):
        with patch.dict("sys.modules", {"ddgs.engines": None}):
            assert multi_search.text_backends() == []

    def test_default_excludes_encyclopedias(self):
        fake = MagicMock()
        fake.ENGINES = {"text": {"brave": 1, "wikipedia": 2, "grokipedia": 3}}
        with patch.dict("sys.modules", {"ddgs.engines": fake}):
            assert multi_search.default_backends() == ["brave"]

    def test_validate_rejects_names_not_registered_for_text(self):
        """ddgs silently auto-selects for unknown names — catch them first."""
        fake = MagicMock()
        fake.ENGINES = {"text": {"brave": 1, "yandex": 2}}
        with patch.dict("sys.modules", {"ddgs.engines": fake}):
            assert multi_search.validate_backends(["brave", "bing"]) == ["bing"]
            assert multi_search.validate_backends(["brave", "yandex"]) == []

    def test_validate_is_a_noop_without_ddgs(self):
        with patch.dict("sys.modules", {"ddgs.engines": None}):
            assert multi_search.validate_backends(["anything"]) == []

    def test_main_rejects_unregistered_backend(self, capsys):
        fake = MagicMock()
        fake.ENGINES = {"text": {"brave": 1}}
        with patch.dict("sys.modules", {"ddgs.engines": fake}):
            with patch.object(
                sys, "argv", ["multi_search", "--query", "x", "--backends", "bing"]
            ):
                with pytest.raises(SystemExit) as excinfo:
                    multi_search.main()
        assert excinfo.value.code == 1
        err = capsys.readouterr().err
        assert "not registered as ddgs text backends: bing" in err
        assert "falls back to auto-selection" in err


# ---------------------------------------------------------------------------
# with_retry()
# ---------------------------------------------------------------------------


class TestWithRetry:
    def test_returns_first_success_without_retrying(self):
        calls = []

        def call():
            calls.append(1)
            return ["hit"]

        assert multi_search.with_retry(call, "x") == ["hit"]
        assert len(calls) == 1

    def test_retries_an_empty_result_then_succeeds(self):
        """A blocked ddgs engine and a zero-hit query look identical here."""
        outcomes = [[], [], ["hit"]]
        assert multi_search.with_retry(lambda: outcomes.pop(0), "x") == ["hit"]

    def test_retries_an_exception_then_succeeds(self):
        state = {"n": 0}

        def call():
            state["n"] += 1
            if state["n"] < 3:
                raise RuntimeError("blocked")
            return ["hit"]

        assert multi_search.with_retry(call, "x") == ["hit"]

    def test_raises_carrying_the_last_failure(self):
        def call():
            raise RuntimeError("403 forbidden")

        with pytest.raises(RuntimeError) as excinfo:
            multi_search.with_retry(call, "brave")
        assert "brave failed after 3 attempts" in str(excinfo.value)
        assert "403 forbidden" in str(excinfo.value)

    def test_attempts_is_honoured(self):
        calls = []
        with pytest.raises(RuntimeError):
            multi_search.with_retry(lambda: calls.append(1), "x", attempts=2)
        assert len(calls) == 2


# ---------------------------------------------------------------------------
# scholarly parsers
# ---------------------------------------------------------------------------


class TestScholarlyParsers:
    def test_openalex_abstract_is_rebuilt_in_position_order(self):
        inverted = {"duty": [2], "transfer": [1], "Property": [0]}
        assert multi_search.openalex_abstract(inverted) == "Property transfer duty"

    def test_openalex_abstract_tolerates_a_missing_index(self):
        assert multi_search.openalex_abstract(None) == ""
        assert multi_search.openalex_abstract([]) == ""

    def test_openalex_prefers_doi_over_landing_page(self):
        payload = {
            "results": [
                {
                    "display_name": "A paper",
                    "doi": "https://doi.org/10.1/x",
                    "id": "https://openalex.org/W1",
                    "primary_location": {"landing_page_url": "https://pub.example/x"},
                    "abstract_inverted_index": {"Hello": [0]},
                }
            ]
        }
        (record,) = multi_search.parse_openalex(payload)
        assert record["url"] == "https://doi.org/10.1/x"
        assert record["title"] == "A paper"
        assert record["snippet"] == "Hello"

    def test_openalex_falls_back_when_there_is_no_doi(self):
        payload = {
            "results": [
                {
                    "display_name": "B",
                    "primary_location": {"landing_page_url": "https://p"},
                },
                {"display_name": "C", "id": "https://openalex.org/W2"},
                {"display_name": "no url at all"},
            ]
        }
        urls = [r["url"] for r in multi_search.parse_openalex(payload)]
        assert urls == ["https://p", "https://openalex.org/W2"]

    def test_crossref_strips_jats_markup_from_the_abstract(self):
        payload = {
            "message": {
                "items": [
                    {
                        "URL": "https://doi.org/10.2/y",
                        "title": ["Second paper"],
                        "abstract": (
                            "<jats:p>Real <jats:italic>text</jats:italic></jats:p>"
                        ),
                    }
                ]
            }
        }
        (record,) = multi_search.parse_crossref(payload)
        assert record["url"] == "https://doi.org/10.2/y"
        assert record["title"] == "Second paper"
        assert record["snippet"] == "Real text"

    def test_crossref_handles_missing_title_and_abstract(self):
        payload = {"message": {"items": [{"URL": "https://doi.org/10.3/z"}]}}
        (record,) = multi_search.parse_crossref(payload)
        assert record["title"] == ""
        assert record["snippet"] == ""

    def test_wikipedia_builds_an_article_url_and_strips_match_markup(self):
        payload = {
            "query": {
                "search": [
                    {
                        "title": "Taxation in Spain",
                        "snippet": 'The <span class="searchmatch">rate</span> is 24%',
                    }
                ]
            }
        }
        (record,) = multi_search.parse_wikipedia_fulltext(payload)
        assert record["url"] == "https://en.wikipedia.org/wiki/Taxation_in_Spain"
        assert record["snippet"] == "The rate is 24%"

    def test_parsers_tolerate_an_empty_payload(self):
        for parse in multi_search._SCHOLARLY_PARSERS.values():
            assert parse({}) == []


# ---------------------------------------------------------------------------
# scholarly engine
# ---------------------------------------------------------------------------


class TestSearchScholarly:
    def test_one_dead_source_does_not_kill_its_wave(self, capsys):
        """openalex and wikipedia share wave A; one failing must not lose both."""

        def fake_fetch_json(url):
            if "openalex" in url:
                raise RuntimeError("502 upstream error")
            if "wikipedia" in url:
                return {"query": {"search": [{"title": "T", "snippet": "s"}]}}
            return {
                "message": {"items": [{"URL": "https://doi.org/1", "title": ["C"]}]}
            }

        with patch.object(multi_search, "_fetch_json", side_effect=fake_fetch_json):
            payload = multi_search.search_scholarly("q", 5)

        urls = [r["url"] for r in payload["results"]]
        assert "https://en.wikipedia.org/wiki/T" in urls
        assert "https://doi.org/1" in urls
        assert "openalex failed" in capsys.readouterr().err

    def test_waves_are_labelled_so_they_cannot_collide_with_ddg(self):
        with patch.object(multi_search, "_fetch_json", return_value={}):
            payload = multi_search.search_scholarly("q", 5)
        cov = payload["coverage"]
        assert cov["wave_a_backends"] == "openalex,wikipedia-fulltext"
        assert cov["wave_b_backends"] == "crossref"
        for entry in cov["waves_failed"]:
            assert entry["wave"].startswith("scholarly:")

    def test_fetch_service_exit_becomes_a_wave_failure_not_a_process_exit(self):
        """A dead fetch service must not discard ddg results already in hand."""
        with patch("scripts.fetch_url.fetch", side_effect=SystemExit(3)):
            payload = multi_search.search_scholarly("q", 5)
        assert payload["results"] == []
        assert payload["coverage"]["single_wave"] is False
        assert payload["coverage"]["waves_ok"] == []


# ---------------------------------------------------------------------------
# merge_coverage()
# ---------------------------------------------------------------------------


class TestMergeCoverage:
    def test_single_engine_keeps_its_block_unchanged(self):
        cov = {"waves_ok": ["A"], "single_wave": True}
        assert multi_search.merge_coverage({"ddg": cov}) is cov

    def test_two_engines_aggregate_into_two_independent_samples(self):
        merged = multi_search.merge_coverage(
            {
                "ddg": {
                    "waves_ok": ["A"],
                    "waves_failed": [{"wave": "B", "error": "x"}],
                    "wave_a_backends": "brave",
                    "wave_b_backends": "yahoo",
                    "returned_by_wave": {"A": 10},
                    "single_wave": True,
                },
                "scholarly": {
                    "waves_ok": ["scholarly:A"],
                    "waves_failed": [],
                    "wave_a_backends": "openalex,wikipedia-fulltext",
                    "wave_b_backends": "crossref",
                    "returned_by_wave": {"scholarly:A": 5},
                    "single_wave": True,
                },
            }
        )
        assert merged["independent_samples"] == 2
        assert merged["single_wave"] is False
        assert merged["waves_ok"] == ["A", "scholarly:A"]
        assert merged["returned_by_wave"] == {"A": 10, "scholarly:A": 5}
        assert merged["wave_a_backends"] == "brave,openalex,wikipedia-fulltext"
        assert set(merged["engines"]) == {"ddg", "scholarly"}

    def test_one_engine_answering_out_of_two_is_still_single_wave(self):
        merged = multi_search.merge_coverage(
            {
                "ddg": {"waves_ok": [], "waves_failed": [{"wave": "A"}]},
                "scholarly": {"waves_ok": ["scholarly:B"], "waves_failed": []},
            }
        )
        assert merged["single_wave"] is True
        assert merged["independent_samples"] == 1
