# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Tests for scripts/fetch_url.py."""

import io
import sys
import urllib.error
from pathlib import Path
from unittest.mock import patch

import pytest

from scripts import _data_paths, fetch_url


@pytest.fixture
def data_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect DATA_ROOT into tmp_path so tests never touch the project."""
    monkeypatch.setattr(_data_paths, "DATA_ROOT", tmp_path)
    return tmp_path


class _FakeResponse:
    """Minimal stand-in for the object urlopen yields as a context manager."""

    def __init__(self, body: bytes, status: int = 200, ctype: str = "text/html"):
        self._body = body
        self.status = status
        self.headers = {"Content-Type": ctype}

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> "_FakeResponse":
        return self

    def __exit__(self, *exc: object) -> None:
        return None


def _html(text: str) -> bytes:
    """HTML whose extracted text clears MIN_HTML_CHARS.

    `render` now downgrades a near-empty HTML extraction to FAILED, so a
    fixture that is realistic prose rather than three words is required to
    exercise the success path at all.
    """
    filler = " Padding sentence to clear the minimum body length threshold."
    return f"<p>{text}</p><p>{filler * 5}</p>".encode()


def _raise_http(code: int, body: str):
    """Build a urlopen replacement that raises HTTPError with `body`."""

    class _Err(urllib.error.HTTPError):
        def __init__(self) -> None:
            hdrs: dict = {}
            super().__init__(
                "http://svc/fetch", code, "err", hdrs, None  # type: ignore[arg-type]
            )

        def read(self) -> bytes:  # type: ignore[override]
            return body.encode()

    def _fake(*args: object, **kwargs: object):
        raise _Err()

    return _fake


# ---------------------------------------------------------------------------
# html_to_text


def test_html_to_text_drops_script_and_style() -> None:
    html = "<html><head><style>p{color:red}</style></head><body>"
    html += "<script>var x=1;</script><p>Real prose.</p></body></html>"
    out = fetch_url.html_to_text(html)
    assert "Real prose." in out
    assert "color:red" not in out
    assert "var x" not in out


def test_html_to_text_inlines_absolute_links_only() -> None:
    html = '<p><a href="https://example.com/a">Abs</a> and <a href="/rel">Rel</a></p>'
    out = fetch_url.html_to_text(html)
    assert "(https://example.com/a)" in out
    assert "/rel)" not in out


def test_html_to_text_collapses_blank_lines() -> None:
    out = fetch_url.html_to_text("<div><p>One</p><p></p><p>Two</p></div>")
    assert "\n\n\n" not in out
    assert "One" in out and "Two" in out


def test_html_to_text_falls_back_to_raw_on_parse_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A parser blow-up must not silently produce an empty source file."""

    def _boom(self: object, data: str) -> None:
        raise ValueError("bad markup")

    monkeypatch.setattr(fetch_url._TextExtractor, "feed", _boom)
    raw = "<p>content</p>"
    assert fetch_url.html_to_text(raw) == raw


# ---------------------------------------------------------------------------
# render


def test_render_writes_header_and_extracts_html() -> None:
    out = fetch_url.render("https://x.test/p", "OK", "text/html", _html("Hi"))
    assert out.startswith("# Fetched: https://x.test/p\n# Date: ")
    assert "# Status: OK" in out
    assert "Hi" in out
    assert "<p>" not in out


def test_render_passes_through_plain_text() -> None:
    out = fetch_url.render("https://x.test/t", "OK", "text/plain", b"a<b")
    assert "a<b" in out


def test_render_marks_binary_content_failed() -> None:
    out = fetch_url.render("https://x.test/f.png", "OK", "image/png", b"\x89PNG")
    assert "# Status: FAILED (binary content-type image/png" in out
    assert "PNG" not in out


def test_render_preserves_existing_failure_status() -> None:
    out = fetch_url.render("https://x.test/p", "FAILED (404: nope)", "", b"")
    assert "# Status: FAILED (404: nope)" in out


def test_render_keeps_status_on_one_line() -> None:
    """A multi-line status would spill markup into the header block."""
    out = fetch_url.render("https://x.test/p", "FAILED (404: <html>\n<body>)", "", b"")
    header = out.split("\n\n")[0].splitlines()
    assert len(header) == 3
    assert header[2].startswith("# Status: FAILED (404: <html> <body>)")


def test_fetch_collapses_html_error_body_into_status() -> None:
    """Upstream error pages are full HTML documents with newlines."""
    body = "<!DOCTYPE html>\n<html>\n<body>Page not found</body>\n</html>"
    with patch.object(fetch_url.urllib.request, "urlopen", _raise_http(404, body)):
        status, _, _ = fetch_url.fetch("https://x.test/missing")
    assert "\n" not in status
    assert status.startswith("FAILED (404: <!DOCTYPE html> <html>")


# ---------------------------------------------------------------------------
# fetch — error classification


def test_fetch_returns_ok_body() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(b"<p>x</p>")
    ):
        status, ctype, body = fetch_url.fetch("https://x.test/p")
    assert status == "OK"
    assert "text/html" in ctype
    assert body == b"<p>x</p>"


def test_fetch_records_upstream_404_as_failed() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(404, "Not Found")
    ):
        status, _, body = fetch_url.fetch("https://x.test/missing")
    assert status.startswith("FAILED (404")
    assert body == b""


def test_fetch_records_service_refusal_as_failed() -> None:
    """403 with a `refused:` body is the service declining one URL."""
    with patch.object(
        fetch_url.urllib.request,
        "urlopen",
        _raise_http(403, "refused: non-public address"),
    ):
        status, _, _ = fetch_url.fetch("https://10.0.0.1/x")
    assert status.startswith("FAILED (403")
    assert "refused" in status


def test_fetch_records_upstream_error_as_failed() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(502, "upstream error: TLS")
    ):
        status, _, _ = fetch_url.fetch("https://x.test/p")
    assert status.startswith("FAILED (502")


def test_fetch_exits_3_on_proxy_policy_denial() -> None:
    """403 without `refused:` is OpenShell's proxy, not the service."""
    with patch.object(
        fetch_url.urllib.request,
        "urlopen",
        _raise_http(403, '{"error":"policy_denied"}'),
    ):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 3


def test_fetch_exits_1_on_bad_request() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", _raise_http(400, "missing url parameter")
    ):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 1


def test_fetch_exits_3_when_service_offline() -> None:
    def _down(*args: object, **kwargs: object):
        raise urllib.error.URLError("connection refused")

    with patch.object(fetch_url.urllib.request, "urlopen", _down):
        with pytest.raises(SystemExit) as exc:
            fetch_url.fetch("https://x.test/p")
    assert exc.value.code == 3


def test_fetch_percent_encodes_the_url() -> None:
    """An unencoded `?` or `&` would truncate the service's own query string."""
    seen: list[str] = []

    def _capture(url: str, *a: object, **k: object) -> _FakeResponse:
        seen.append(url)
        return _FakeResponse(b"ok", ctype="text/plain")

    with patch.object(fetch_url.urllib.request, "urlopen", _capture):
        fetch_url.fetch("https://x.test/s?q=1&r=2")
    assert "q%3D1%26r%3D2" in seen[0]
    assert seen[0].count("?") == 1


# ---------------------------------------------------------------------------
# check_service


def test_check_service_ok() -> None:
    with patch.object(
        fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(b"", 200)
    ):
        assert fetch_url.check_service() == 0


def test_check_service_offline_returns_3() -> None:
    def _down(*args: object, **kwargs: object):
        raise urllib.error.URLError("refused")

    with patch.object(fetch_url.urllib.request, "urlopen", _down):
        assert fetch_url.check_service() == 3


# ---------------------------------------------------------------------------
# main


def test_main_writes_fetched_file(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    argv = ["fetch_url", "topic", "fetched/p.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request,
            "urlopen",
            lambda *a, **k: _FakeResponse(_html("Data")),
        ):
            fetch_url.main()
    written = (data_root / "topic" / "fetched" / "p.md").read_text()
    assert "# Fetched: https://x.test/p" in written
    assert "Data" in written


def test_main_requires_bootstrapped_slug_root(data_root: Path) -> None:
    argv = ["fetch_url", "missing", "fetched/p.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 1


def test_main_rejects_slug_escape(data_root: Path) -> None:
    argv = ["fetch_url", "topic", "../escape.md", "https://x.test/p"]
    with patch.object(sys, "argv", argv):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 1


# ---------------------------------------------------------------------------
# live


@pytest.mark.live
def test_live_fetch_service_health() -> None:
    """Manual sanity check — requires the host fetch service running."""
    assert fetch_url.check_service() == 0


# ---------------------------------------------------------------------------
# 403 disambiguation — three sources, opposite handling


def test_upstream_403_is_recorded_not_fatal() -> None:
    """Bot-protection 403s are routine; they must not abort the run.

    Regression: an upstream Cloudflare block was misread as a proxy policy
    denial and exited 3, killing a batch mid-fetch.
    """
    body = "<html><head><title>403 Forbidden</title></head><body>Denied</body></html>"
    with patch.object(fetch_url.urllib.request, "urlopen", _raise_http(403, body)):
        status, _, _ = fetch_url.fetch("https://blocked.test/p")
    assert status.startswith("FAILED (403")


def test_proxy_denial_detected_by_marker() -> None:
    assert fetch_url.is_proxy_denial(403, '{"error":"policy_denied"}')
    assert fetch_url.is_proxy_denial(403, "GET x not permitted by policy")


def test_non_proxy_403_bodies_are_not_denials() -> None:
    assert not fetch_url.is_proxy_denial(403, "refused: non-public address")
    assert not fetch_url.is_proxy_denial(403, "<html>403 Forbidden</html>")
    assert not fetch_url.is_proxy_denial(404, "policy_denied")


# ---------------------------------------------------------------------------
# Encyclopedia reference mining — deterministic, not model-driven


def test_is_encyclopedia_matches_any_language_subdomain() -> None:
    assert fetch_url.is_encyclopedia("https://en.wikipedia.org/wiki/X")
    assert fetch_url.is_encyclopedia("https://fr.wikipedia.org/wiki/X")
    assert fetch_url.is_encyclopedia("https://grokipedia.com/page/X")
    assert not fetch_url.is_encyclopedia("https://www.irs.gov/pub")
    assert not fetch_url.is_encyclopedia("https://notwikipedia.org.evil.com/x")


def test_extracts_mediawiki_external_links_only() -> None:
    """MediaWiki marks citations with class=external; internal links are noise."""
    html = """
    <a href="/wiki/Internal">internal</a>
    <a href="https://en.wikipedia.org/wiki/Other">same host</a>
    <a class="external text" href="https://www.irs.gov/pub/p527">ref 1</a>
    <a class="external autonumber" href="https://eur-lex.europa.eu/x">ref 2</a>
    <a href="https://example.com/unmarked">unmarked</a>
    """
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://www.irs.gov/pub/p527", "https://eur-lex.europa.eu/x"]


def test_falls_back_to_cross_host_links_when_unmarked() -> None:
    """Grokipedia is not MediaWiki and has no `external` class marker."""
    html = '<a href="https://www.oecd.org/report">r</a><a href="/rel">x</a>'
    refs = fetch_url.extract_reference_urls(html, "https://grokipedia.com/page/X")
    assert refs == ["https://www.oecd.org/report"]


def test_filters_infrastructure_hosts() -> None:
    html = """
    <a class="external" href="https://commons.wikimedia.org/x">commons</a>
    <a class="external" href="https://www.wikidata.org/y">wikidata</a>
    <a class="external" href="https://creativecommons.org/licenses/">cc</a>
    <a class="external" href="https://www.bde.es/report">real source</a>
    """
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://www.bde.es/report"]


def test_reference_urls_are_deduplicated_in_order() -> None:
    html = (
        '<a class="external" href="https://a.test/1">a</a>'
        '<a class="external" href="https://b.test/2">b</a>'
        '<a class="external" href="https://a.test/1">a again</a>'
    )
    refs = fetch_url.extract_reference_urls(html, "https://en.wikipedia.org/wiki/X")
    assert refs == ["https://a.test/1", "https://b.test/2"]


def test_malformed_markup_yields_no_refs_rather_than_raising(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _boom(self: object, data: str) -> None:
        raise ValueError("bad markup")

    monkeypatch.setattr(fetch_url._RefExtractor, "feed", _boom)
    assert fetch_url.extract_reference_urls("<a>", "https://en.wikipedia.org/x") == []


def test_main_writes_refs_sidecar_for_encyclopedia(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    html = _html("Text") + b'<a class="external" href="https://www.irs.gov/p527">r</a>'
    argv = ["fetch_url", "topic", "fetched/wiki.md", "https://en.wikipedia.org/wiki/X"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(html)
        ):
            fetch_url.main()
    sidecar = data_root / "topic" / "fetched" / "wiki.md.refs"
    assert sidecar.read_text().splitlines() == ["https://www.irs.gov/p527"]


def test_main_writes_no_sidecar_for_ordinary_pages(data_root: Path) -> None:
    (data_root / "topic").mkdir()
    html = _html("Text") + b'<a href="https://elsewhere.test/x">link</a>'
    argv = ["fetch_url", "topic", "fetched/gov.md", "https://www.irs.gov/pub/p527"]
    with patch.object(sys, "argv", argv):
        with patch.object(
            fetch_url.urllib.request, "urlopen", lambda *a, **k: _FakeResponse(html)
        ):
            fetch_url.main()
    assert not (data_root / "topic" / "fetched" / "gov.md.refs").exists()


# ---------------------------------------------------------------------------
# PDF extraction — the Tier 1 half of a source pool


def _pdf(text: str) -> bytes:
    """A real one-page PDF carrying `text`, built with the shipped writer."""
    from pypdf import PdfWriter
    from pypdf.generic import (
        ArrayObject,
        DecodedStreamObject,
        DictionaryObject,
        NameObject,
        NumberObject,
    )

    writer = PdfWriter()
    page = writer.add_blank_page(width=200, height=200)
    stream = DecodedStreamObject()
    escaped = text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    stream.set_data(f"BT /F1 12 Tf 10 100 Td ({escaped}) Tj ET".encode())
    font = DictionaryObject(
        {
            NameObject("/Type"): NameObject("/Font"),
            NameObject("/Subtype"): NameObject("/Type1"),
            NameObject("/BaseFont"): NameObject("/Helvetica"),
        }
    )
    page[NameObject("/Contents")] = writer._add_object(stream)
    page[NameObject("/Resources")] = DictionaryObject(
        {NameObject("/Font"): DictionaryObject({NameObject("/F1"): font})}
    )
    page[NameObject("/MediaBox")] = ArrayObject(
        [NumberObject(0), NumberObject(0), NumberObject(200), NumberObject(200)]
    )
    buf = io.BytesIO()
    writer.write(buf)
    return buf.getvalue()


def test_render_extracts_pdf_text() -> None:
    out = fetch_url.render(
        "https://x.test/law.pdf", "OK", "application/pdf", _pdf("Ley 6043")
    )
    assert "# Status: OK" in out
    assert "Ley 6043" in out


def test_render_detects_pdf_by_magic_bytes_when_mislabelled() -> None:
    """Hosts serve PDFs as application/octet-stream often enough to matter."""
    raw = _pdf("Decreto-Lei 97/2026")
    out = fetch_url.render("https://x.test/d", "OK", "application/octet-stream", raw)
    assert "# Status: OK" in out
    assert "97/2026" in out


def test_render_reports_scanned_pdf_distinctly() -> None:
    """A page with no text layer must not read as `the source said nothing`."""
    from pypdf import PdfWriter

    writer = PdfWriter()
    writer.add_blank_page(width=200, height=200)
    buf = io.BytesIO()
    writer.write(buf)
    out = fetch_url.render(
        "https://x.test/scan.pdf", "OK", "application/pdf", buf.getvalue()
    )
    assert "# Status: FAILED (no text layer" in out


def test_render_records_malformed_pdf_as_parse_error() -> None:
    out = fetch_url.render(
        "https://x.test/b.pdf", "OK", "application/pdf", b"%PDF-1.7 junk"
    )
    assert "# Status: FAILED (pdf parse error:" in out
    header = out.split("\n\n")[0].splitlines()
    assert len(header) == 3


def test_render_reports_pdf_truncation(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(fetch_url, "MAX_PDF_PAGES", 1)
    from pypdf import PdfReader, PdfWriter

    writer = PdfWriter()
    writer.append(PdfReader(io.BytesIO(_pdf("First page"))))
    writer.add_blank_page(width=200, height=200)
    buf = io.BytesIO()
    writer.write(buf)
    out = fetch_url.render(
        "https://x.test/big.pdf", "OK", "application/pdf", buf.getvalue()
    )
    assert "truncated at 1 of 2 pages" in out


# ---------------------------------------------------------------------------
# JS-rendered pages — an OK fetch of nothing is worse than a clean failure


def test_render_fails_near_empty_html() -> None:
    out = fetch_url.render(
        "https://x.test/js", "OK", "text/html", b"<div id='root'></div>"
    )
    assert "# Status: FAILED (empty after extraction, 0 chars" in out


def test_render_keeps_short_json_which_is_legitimately_small() -> None:
    """The emptiness rule is HTML-only; a terse API answer is a real answer."""
    out = fetch_url.render("https://x.test/a", "OK", "application/json", b'{"n":1}')
    assert "# Status: OK" in out
    assert '{"n":1}' in out


# ---------------------------------------------------------------------------
# ascii_url — a literal non-ASCII character 502s the fetch service


def test_ascii_url_percent_encodes_non_ascii_path() -> None:
    out = fetch_url.ascii_url("https://www.notaires.fr/fr/départements")
    assert out == "https://www.notaires.fr/fr/d%C3%A9partements"


def test_ascii_url_idna_encodes_the_host() -> None:
    assert fetch_url.ascii_url("https://münchen.de/x") == "https://xn--mnchen-3ya.de/x"


def test_ascii_url_leaves_encoded_sequences_alone() -> None:
    """Double-encoding would turn a working URL into a 404."""
    url = "https://x.test/a%20b?q=1&r=2#f"
    assert fetch_url.ascii_url(url) == url


def test_fetch_sends_ascii_form(monkeypatch: pytest.MonkeyPatch) -> None:
    seen: list[str] = []

    def _capture(url: str, *a: object, **k: object) -> _FakeResponse:
        seen.append(url)
        return _FakeResponse(b"ok", ctype="text/plain")

    with patch.object(fetch_url.urllib.request, "urlopen", _capture):
        fetch_url.fetch("https://x.test/départements")
    assert all(ord(c) < 128 for c in seen[0])
    assert "d%25C3%25A9partements" in seen[0]


# ---------------------------------------------------------------------------
# url_to_name / --batch


def test_url_to_name_is_filesystem_safe_and_stable() -> None:
    name = fetch_url.url_to_name("https://boe.es/buscar/act.php?id=BOE-A-1889-4763")
    assert name.endswith(".md")
    assert set(name) <= set(
        "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-"
    )
    assert name == fetch_url.url_to_name(
        "https://boe.es/buscar/act.php?id=BOE-A-1889-4763"
    )


def test_url_to_name_does_not_collide_on_long_shared_prefix() -> None:
    """Truncation alone would let one gazette document overwrite another."""
    base = "https://www.gazzettaufficiale.it/atto/serie_generale/caricaDettaglio?id="
    assert fetch_url.url_to_name(base + "aaa") != fetch_url.url_to_name(base + "bbb")


def test_batch_fetches_every_url_and_counts_failures(
    data_root: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    (data_root / "topic").mkdir()
    calls: list[str] = []

    def _fake(url: str, *a: object, **k: object) -> _FakeResponse:
        calls.append(url)
        if "bad" in url:
            return _FakeResponse(b"<div></div>")
        return _FakeResponse(_html("Real prose"))

    argv = ["fetch_url", "--batch", "topic"]
    stdin = io.StringIO("https://a.test/good\n\n# comment\nhttps://b.test/bad\n")
    with patch.object(sys, "argv", argv), patch.object(sys, "stdin", stdin):
        with patch.object(fetch_url.urllib.request, "urlopen", _fake):
            fetch_url.main()
    assert len(calls) == 2
    captured = capsys.readouterr()
    assert "batch complete: ok=1 failed=1" in captured.err
    written = list((data_root / "topic" / "fetched").glob("*.md"))
    assert len(written) == 2


def test_batch_requires_bootstrapped_slug_root(data_root: Path) -> None:
    argv = ["fetch_url", "--batch", "missing"]
    with patch.object(sys, "argv", argv), patch.object(sys, "stdin", io.StringIO("")):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 1


# ---------------------------------------------------------------------------
# OCR fallback for scanned PDFs


def _scanned_pdf(lines: list[str]) -> bytes:
    """A PDF whose pages are images — no text layer, like a real scan."""
    from PIL import Image, ImageDraw, ImageFont

    img = Image.new("RGB", (1240, 120 + 70 * len(lines)), "white")
    draw = ImageDraw.Draw(img)
    font = ImageFont.load_default(size=34)
    for i, line in enumerate(lines):
        draw.text((40, 40 + i * 70), line, fill="black", font=font)
    buf = io.BytesIO()
    img.save(buf, format="PDF", resolution=150)
    return buf.getvalue()


def _has_ocr() -> bool:
    import importlib.util

    return all(
        importlib.util.find_spec(m) is not None
        for m in ("pypdfium2", "rapidocr_onnxruntime", "PIL")
    )


ocr_only = pytest.mark.skipif(not _has_ocr(), reason='needs pip install -e ".[ocr]"')


@ocr_only
def test_scanned_pdf_is_read_by_ocr() -> None:
    raw = _scanned_pdf(["Artigo 17.o-A do CIMT", "A taxa e de 7,5% sobre o valor."])
    out = fetch_url.render("https://x.test/scan.pdf", "OK", "application/pdf", raw)
    assert "7,5%" in out
    assert "CIMT" in out


@ocr_only
def test_ocr_output_is_marked_as_a_transcription() -> None:
    """An audit agent must not read OCR text as a quotable source string.

    A misread digit produces a plausible wrong number, and the audit compares
    the deliverable against this same file — so the error would be confirmed,
    not caught. The status line is the only thing standing in the way.
    """
    raw = _scanned_pdf(["Coima ate EUR 20.000"])
    out = fetch_url.render("https://x.test/scan.pdf", "OK", "application/pdf", raw)
    status = out.splitlines()[2]
    assert status.startswith("# Status: OK (OCR")
    assert "transcription, not verbatim source" in status


@ocr_only
def test_ocr_reports_truncation(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(fetch_url, "MAX_OCR_PAGES", 1)
    from PIL import Image

    page = Image.new("RGB", (400, 200), "white")
    buf = io.BytesIO()
    page.save(buf, format="PDF", save_all=True, append_images=[page])
    out = fetch_url.ocr_pdf(buf.getvalue())[0]
    assert "truncated at 1 of 2 pages" in out or out.startswith("FAILED")


def test_ocr_absence_names_the_install(monkeypatch: pytest.MonkeyPatch) -> None:
    """Without the extra, a scanned PDF must say so and say how to fix it."""
    monkeypatch.setitem(sys.modules, "pypdfium2", None)
    status, body = fetch_url.ocr_pdf(b"%PDF-1.7")
    assert status.startswith("FAILED (no text layer")
    assert 'pip install -e ".[ocr]"' in status
    assert body == ""


def test_ocr_render_failure_is_recorded_not_raised() -> None:
    status, body = fetch_url.ocr_pdf(b"not a pdf at all")
    assert status.startswith("FAILED (")
    assert body == ""


# ---------------------------------------------------------------------------
# Dependency preflight — catch a missing extractor before the run, not after


def test_check_dependencies_flags_missing_required(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import importlib.util

    real = importlib.util.find_spec
    monkeypatch.setattr(
        importlib.util, "find_spec", lambda n: None if n == "pypdf" else real(n)
    )
    lines, ok = fetch_url.check_dependencies()
    assert not ok
    assert any("MISSING  pypdf" in line for line in lines)
    assert any("pip install -e ." in line for line in lines)


def test_check_dependencies_optional_absence_is_not_a_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """No OCR extra is a reduced capability, not a broken install."""
    import importlib.util

    real = importlib.util.find_spec
    monkeypatch.setattr(
        importlib.util,
        "find_spec",
        lambda n: None if n in ("pypdfium2", "rapidocr_onnxruntime") else real(n),
    )
    lines, ok = fetch_url.check_dependencies()
    assert ok
    assert any('pip install -e ".[ocr]"' in line for line in lines)


def test_check_exits_3_when_a_required_dependency_is_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A healthy service with no PDF extractor is still a failed preflight."""
    monkeypatch.setattr(fetch_url, "check_service", lambda: 0)
    monkeypatch.setattr(fetch_url, "check_dependencies", lambda: (["MISSING"], False))
    with patch.object(sys, "argv", ["fetch_url", "--check"]):
        with pytest.raises(SystemExit) as exc:
            fetch_url.main()
    assert exc.value.code == 3
