# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for scripts/bootstrap_tmp.sh.

Skipped on systems without `bash` on PATH (e.g., bare Windows without
git-bash). The script itself is portable bash; tests just need a runner.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

BOOTSTRAP = Path(__file__).resolve().parent.parent / "scripts" / "bootstrap_tmp.sh"

pytestmark = pytest.mark.skipif(
    shutil.which("bash") is None,
    reason="bash not available on PATH",
)


def _run(args: list[str], project_root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(BOOTSTRAP), *args],
        cwd=str(project_root),
        env={"PROJECT_ROOT": str(project_root), "PATH": _path_env()},
        capture_output=True,
        text=True,
        check=False,
    )


def _path_env() -> str:
    import os

    return os.environ.get("PATH", "")


class TestSuccessfulRuns:
    def test_creates_parent_with_gitignore(self, tmp_path: Path) -> None:
        result = _run(["topic-a"], tmp_path)
        assert result.returncode == 0, result.stderr
        parent = tmp_path / ".tmp-cited-research"
        assert parent.is_dir()
        gitignore = parent / ".gitignore"
        assert gitignore.is_file()
        assert gitignore.read_text(encoding="utf-8") == "*"

    def test_creates_slug_subdir(self, tmp_path: Path) -> None:
        _run(["topic-a"], tmp_path)
        slug_dir = tmp_path / ".tmp-cited-research" / "topic-a"
        assert slug_dir.is_dir()

    def test_emits_ready_message(self, tmp_path: Path) -> None:
        result = _run(["topic-a"], tmp_path)
        assert "bootstrap_tmp:" in result.stdout
        assert "ready (wiped)" in result.stdout

    def test_wipes_existing_slug_contents(self, tmp_path: Path) -> None:
        parent = tmp_path / ".tmp-cited-research"
        slug_dir = parent / "topic-a"
        slug_dir.mkdir(parents=True)
        stale = slug_dir / "stale.md"
        stale.write_text("old content", encoding="utf-8")

        _run(["topic-a"], tmp_path)

        assert slug_dir.is_dir()
        assert not stale.exists()

    def test_leaves_sibling_slugs_intact(self, tmp_path: Path) -> None:
        parent = tmp_path / ".tmp-cited-research"
        keep = parent / "keep-me"
        keep.mkdir(parents=True)
        keep_file = keep / "keep.md"
        keep_file.write_text("preserved", encoding="utf-8")

        _run(["wipe-me"], tmp_path)

        assert keep_file.read_text(encoding="utf-8") == "preserved"
        assert (parent / "wipe-me").is_dir()

    def test_idempotent_when_gitignore_already_exists(self, tmp_path: Path) -> None:
        # First run creates everything.
        _run(["topic-a"], tmp_path)
        # Second run on same slug must succeed without surprises.
        result = _run(["topic-a"], tmp_path)
        assert result.returncode == 0, result.stderr
        gitignore = tmp_path / ".tmp-cited-research" / ".gitignore"
        assert gitignore.read_text(encoding="utf-8") == "*"


class TestArgumentHandling:
    def test_missing_arg_is_usage_error(self, tmp_path: Path) -> None:
        result = _run([], tmp_path)
        assert result.returncode == 2
        assert "usage:" in result.stderr

    def test_too_many_args_is_usage_error(self, tmp_path: Path) -> None:
        result = _run(["topic-a", "extra"], tmp_path)
        assert result.returncode == 2
        assert "usage:" in result.stderr


class TestSlugValidation:
    @pytest.mark.parametrize(
        "slug",
        [
            "",
            "UPPERCASE",
            "Topic-Mixed",
            "-leading",
            "trailing-",
            "double--dash",
            "has/slash",
            "has\\slash",
            "..",
            "../escape",
            ".hidden",
            "$HOME",
            "${HOME}",
            "with space",
            "with.period",
            "semi;colon",
            "pipe|char",
            # quote/backtick characters are mangled by Windows subprocess
            # argv handling before bash sees them, so testing rejection of
            # those here would actually test subprocess quoting, not the
            # script. The bash regex still rejects them on POSIX systems
            # if they survive to argv.
        ],
    )
    def test_rejects_invalid_slug(self, slug: str, tmp_path: Path) -> None:
        result = _run([slug], tmp_path)
        assert result.returncode == 1, (
            f"slug {slug!r} should have been rejected; got "
            f"rc={result.returncode}, stderr={result.stderr!r}"
        )
        assert "invalid slug" in result.stderr

    @pytest.mark.parametrize(
        "slug",
        [
            "a",
            "topic",
            "queue-system",
            "clarinet-vs-french-horn",
            "otel-v2",
            "a1b2c3",
        ],
    )
    def test_accepts_kebab_case(self, slug: str, tmp_path: Path) -> None:
        result = _run([slug], tmp_path)
        assert result.returncode == 0, (
            f"slug {slug!r} should have been accepted; got "
            f"rc={result.returncode}, stderr={result.stderr!r}"
        )
