# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Tests for scripts/run_report.py."""

import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from scripts import _data_paths, run_report


@pytest.fixture
def run_dirs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Build an empty run tree and point DATA_ROOT at it."""
    data_root = tmp_path / "tmp"
    monkeypatch.setattr(_data_paths, "DATA_ROOT", data_root)
    slug_root = data_root / "topic"
    (slug_root / "fetched").mkdir(parents=True)
    (slug_root / "search").mkdir()
    deliverable = tmp_path / "research" / "topic"
    (deliverable / "audit").mkdir(parents=True)
    return slug_root, deliverable


def _fetched(slug_root: Path, name: str, status: str) -> None:
    (slug_root / "fetched" / name).write_text(
        f"# Fetched: https://x.test/{name}\n# Date: now\n# Status: {status}\n\nbody\n"
    )


# ---------------------------------------------------------------------------
# agents


def test_agent_outcomes_and_dropped_list(run_dirs):
    slug_root, _ = run_dirs
    (slug_root / "agents.tsv").write_text(
        "# name\tmode\tstatus\n"
        "d1\tpropose\tok\n"
        "d2\tpropose\tok\n"
        "d3\ttriage\terror: no response\n"
    )
    outcomes, dropped = run_report.read_agents(slug_root)
    assert outcomes["ok"] == 2
    assert len(dropped) == 1
    assert "d3 (triage)" in dropped[0]


def test_missing_agents_file_is_not_an_error(run_dirs):
    slug_root, _ = run_dirs
    assert run_report.read_agents(slug_root) == (run_report.Counter(), [])


# ---------------------------------------------------------------------------
# search


def test_search_counts_engines_and_single_wave(run_dirs):
    slug_root, _ = run_dirs
    (slug_root / "search" / "q1.json").write_text(
        '{"results": [{"url": "https://a"}, {"url": "https://b"}],'
        ' "coverage": {"wave_a_backends": "brave,google",'
        ' "wave_b_backends": "yandex", "single_wave": false,'
        ' "unique_by_wave": {"A": 2}}}'
    )
    (slug_root / "search" / "q2.json").write_text(
        '{"results": [{"url": "https://c"}],'
        ' "coverage": {"wave_a_backends": "brave", "wave_b_backends": "yandex",'
        ' "single_wave": true, "unique_by_wave": {"A": 1}}}'
    )
    stats = run_report.read_search(slug_root)
    assert stats.queries == 2
    assert stats.results == 3
    assert stats.single_wave == 1
    assert set(stats.engines) == {"brave", "google", "yandex"}
    assert stats.unique_by_wave["A"] == 3


def test_unparsable_search_file_is_counted_not_swallowed(run_dirs):
    slug_root, _ = run_dirs
    (slug_root / "search" / "bad.json").write_text("{not json")
    (slug_root / "search" / "arr.json").write_text("[1,2]")
    stats = run_report.read_search(slug_root)
    assert stats.queries == 0
    assert stats.unparsable == 2


# ---------------------------------------------------------------------------
# fetch


def test_fetch_tallies_status_and_failure_codes(run_dirs):
    slug_root, _ = run_dirs
    _fetched(slug_root, "a.md", "OK")
    _fetched(slug_root, "b.md", "FAILED (403: blocked)")
    _fetched(slug_root, "c.md", "FAILED (404: gone)")
    (slug_root / "fetched" / "a.md.refs").write_text("https://ref1\nhttps://ref2\n")
    stats = run_report.read_fetched(slug_root)
    assert (stats.total, stats.ok, stats.failed) == (3, 1, 2)
    assert stats.reasons["403"] == 1 and stats.reasons["404"] == 1
    assert stats.refs == 2


# ---------------------------------------------------------------------------
# citations


def test_citation_tiers_orphans_and_access_failures(run_dirs):
    _, deliverable = run_dirs
    (deliverable / "citations.md").write_text(
        "**[1]** A\n**Tier:** 1\nnote\n\n"
        "**[2]** B\n**Tier:** 4\n**Access:** FAILED (404)\n\n"
        "**[3]** C\n**Tier:** 2\n"
    )
    (deliverable / "analysis.md").write_text("Claim [1] and [2].")
    stats = run_report.read_citations(deliverable)
    assert stats.defined == 3
    assert stats.cited == 2  # [3] is an orphan
    assert stats.access_failed == 1
    assert stats.tiers == {"Tier 1": 1, "Tier 4": 1, "Tier 2": 1}


def test_audit_dir_is_excluded_from_cited_scan(run_dirs):
    """Grades quoted in the audit must not count as prose citations."""
    _, deliverable = run_dirs
    (deliverable / "citations.md").write_text("**[1]** A\n**Tier:** 1\n")
    (deliverable / "audit" / "citation-audit.md").write_text("[1] VERIFIED")
    assert run_report.read_citations(deliverable).cited == 0


# ---------------------------------------------------------------------------
# audit grades


def test_grade_ledger_is_preferred(run_dirs):
    _, deliverable = run_dirs
    (deliverable / "audit" / "citation-audit.md").write_text(
        "## Findings\n**Grade: INACCURATE** — something\n\n"
        "## Grade Ledger\n[1] VERIFIED\n[2] VERIFIED\n[3] INACCURATE\n"
    )
    grades = run_report.read_audit(deliverable)
    assert grades == {"VERIFIED": 2, "INACCURATE": 1}


def test_falls_back_to_prose_grades_without_a_ledger(run_dirs):
    _, deliverable = run_dirs
    (deliverable / "audit" / "citation-audit.md").write_text(
        "**Grade: VERIFIED** — ok\n**Grade: PARTIAL** — hmm\n"
    )
    assert run_report.read_audit(deliverable) == {"VERIFIED": 1, "PARTIAL": 1}


def test_unknown_grade_words_are_ignored(run_dirs):
    _, deliverable = run_dirs
    (deliverable / "audit" / "citation-audit.md").write_text(
        "## Grade Ledger\n[1] VERIFIED\n[2] SPLENDID\n"
    )
    assert run_report.read_audit(deliverable) == {"VERIFIED": 1}


# ---------------------------------------------------------------------------
# report assembly


def test_report_flags_signal_loss_and_unaudited_citations(run_dirs):
    slug_root, deliverable = run_dirs
    (slug_root / "agents.tsv").write_text("a\tpropose\tok\nb\ttriage\ttimeout\n")
    _fetched(slug_root, "a.md", "OK")
    (deliverable / "citations.md").write_text(
        "**[1]** A\n**Tier:** 1\n\n**[2]** B\n**Tier:** 2\n"
    )
    (deliverable / "analysis.md").write_text("[1] [2]")
    (deliverable / "audit" / "citation-audit.md").write_text(
        "## Grade Ledger\n[1] VERIFIED\n"
    )
    out = run_report.build_report("topic", slug_root, deliverable)
    assert "lost 1 (50% signal loss)" in out
    assert "b (triage): timeout" in out
    assert "1 citations never audited" in out
    assert "1 verified (100%)" in out


def test_report_states_what_is_missing_rather_than_omitting_it(run_dirs):
    slug_root, deliverable = run_dirs
    out = run_report.build_report("topic", slug_root, deliverable)
    assert "no agents.tsv" in out
    assert "no search/*.json" in out
    assert "no fetched pages found" in out
    assert "no citations.md found" in out
    assert "no graded citations" in out


def test_main_exits_nonzero_when_nothing_exists(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(_data_paths, "DATA_ROOT", tmp_path / "nope")
    monkeypatch.chdir(tmp_path)
    with patch.object(sys, "argv", ["run_report", "ghost"]):
        with pytest.raises(SystemExit) as exc:
            run_report.main()
    assert exc.value.code == 1
    assert "Error: neither" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# presentation: ordinal scales keep their order, HTTP codes are explained


def test_tiers_print_in_scale_order_not_frequency_order(run_dirs):
    """Tier 3 being commonest must not push it above Tier 1 in the list."""
    _, deliverable = run_dirs
    (deliverable / "citations.md").write_text(
        "**[1]** A\n**Tier:** 3\n\n**[2]** B\n**Tier:** 3\n\n"
        "**[3]** C\n**Tier:** 3\n\n**[4]** D\n**Tier:** 1\n"
    )
    out = run_report.build_report("topic", run_dirs[0], deliverable)
    tier_lines = [ln for ln in out.splitlines() if ln.strip().startswith("Tier ")]
    assert [ln.split()[1] for ln in tier_lines] == ["1", "2", "3", "4"]


def test_absent_tier_still_prints_as_zero(run_dirs):
    """No Tier 1 sources is a finding; omitting the row would hide it."""
    _, deliverable = run_dirs
    (deliverable / "citations.md").write_text("**[1]** A\n**Tier:** 4\n")
    out = run_report.build_report("topic", run_dirs[0], deliverable)
    tier1 = [ln for ln in out.splitlines() if ln.strip().startswith("Tier 1")]
    assert tier1, "Tier 1 row must print even with no Tier 1 citations"
    assert tier1[0].split() == ["Tier", "1", "0", "(0%)"]


def test_http_failure_codes_are_glossed(run_dirs):
    slug_root, deliverable = run_dirs
    _fetched(slug_root, "a.md", "FAILED (403: blocked)")
    _fetched(slug_root, "b.md", "FAILED (502: upstream)")
    out = run_report.build_report("topic", slug_root, deliverable)
    assert "failures by HTTP status" in out
    assert "blocked (bot protection or forbidden)" in out
    assert "upstream error (service could not reach the site)" in out


def test_grades_print_best_to_worst_not_by_count(run_dirs):
    _, deliverable = run_dirs
    (deliverable / "audit" / "citation-audit.md").write_text(
        "## Grade Ledger\n[1] INACCURATE\n[2] INACCURATE\n[3] VERIFIED\n"
    )
    out = run_report.build_report("topic", run_dirs[0], deliverable)
    grade_lines = [
        ln.strip().split()[0]
        for ln in out.splitlines()
        if ln.strip().startswith(("VERIFIED", "INACCURATE", "PARTIAL"))
    ]
    assert grade_lines == ["VERIFIED", "INACCURATE"]


def test_engines_and_codes_still_sort_by_frequency(run_dirs):
    """Non-ordinal categories keep frequency ordering — that is informative."""
    counter = run_report.Counter({"rare": 1, "common": 9, "mid": 5})
    rows = run_report._rows("engines", counter)
    assert [r.split()[0] for r in rows] == ["common", "mid", "rare"]
