# Generated By: Claude Code (Claude Opus 5)
"""Tests for scripts/run_meta.py — run scoping and subagent token accounting.

Both behaviours here were regressions found in the field. A run measured at 1.7h
reported 173.8h and a 15x token count because nothing bounded the transcript
read; and every run after the CLI changed its subagent-usage rendering reported
zero subagent tokens because the regex still matched only the older form.
"""

import json
from pathlib import Path

import pytest

from scripts import run_meta


def _record(ts: str, *, text: str = "", usage: dict | None = None, rtype: str) -> str:
    msg: dict = {"role": "assistant" if rtype == "assistant" else "user"}
    if usage is not None:
        msg["usage"] = usage
        msg["model"] = "claude-opus-5"
    if text:
        msg["content"] = text
    return json.dumps({"timestamp": ts, "type": rtype, "message": msg})


@pytest.fixture
def proj(tmp_path: Path) -> Path:
    (tmp_path / "p").mkdir()
    return tmp_path / "p"


# ---------------------------------------------------------------------------
# subagent token formats


def test_counts_both_subagent_renderings(proj: Path):
    """The tag form and the colon form both count, and both land in the total."""
    (proj / "s.jsonl").write_text(
        "\n".join(
            [
                _record(
                    "2026-01-01T00:00:00Z",
                    text="<subagent_tokens>1000</subagent_tokens>",
                    rtype="user",
                ),
                _record(
                    "2026-01-01T00:01:00Z",
                    text="subagent_tokens: 2500\\ntool_uses: 4",
                    rtype="user",
                ),
            ]
        )
    )
    stats = run_meta.read_tokens(proj)
    assert stats.subagent_count == 2
    assert stats.subagent_tokens == 3500


def test_colon_form_counts_without_a_trailing_tool_uses(proj: Path):
    """Anchoring on `tool_uses` was measured to drop real results."""
    (proj / "s.jsonl").write_text(
        _record("2026-01-01T00:00:00Z", text="subagent_tokens: 77", rtype="user")
    )
    assert run_meta.read_tokens(proj).subagent_tokens == 77


def test_assistant_prose_quoting_the_marker_is_not_counted(proj: Path):
    """SKILL.md requires pasting the report — which prints the literal — into
    the reply, so assistant records routinely contain it as prose."""
    (proj / "s.jsonl").write_text(
        "\n".join(
            [
                _record(
                    "2026-01-01T00:00:00Z",
                    text="subagent_tokens: 500",
                    rtype="user",
                ),
                _record(
                    "2026-01-01T00:02:00Z",
                    text="the report said subagent_tokens: 7,596,926 across 92",
                    rtype="assistant",
                ),
            ]
        )
    )
    stats = run_meta.read_tokens(proj)
    assert stats.subagent_count == 1
    assert stats.subagent_tokens == 500


# ---------------------------------------------------------------------------
# run_start


def test_started_marker_wins(tmp_path: Path):
    root = tmp_path / "slug"
    (root / "search").mkdir(parents=True)
    (root / "search" / "q.json").write_text("{}")
    (root / "started").write_text("2026-08-21T16:03:16.123Z\n")
    stamp, signal = run_meta.run_start(root)
    assert stamp == "2026-08-21T16:03:16.123Z"
    assert "started" in signal


def test_falls_back_to_fetched_date_header(tmp_path: Path):
    """Content-based fallback, for runs bootstrapped before the marker existed."""
    root = tmp_path / "slug"
    (root / "fetched").mkdir(parents=True)
    (root / "fetched" / "b.md").write_text(
        "# Fetched: https://x.test/b\n# Date: 2026-08-21T17:00:00Z\n# Status: OK\n"
    )
    (root / "fetched" / "a.md").write_text(
        "# Fetched: https://x.test/a\n# Date: 2026-08-21T16:16:22Z\n# Status: OK\n"
    )
    stamp, signal = run_meta.run_start(root)
    assert stamp == "2026-08-21T16:16:22Z"
    assert "Date" in signal


def test_returns_empty_when_nothing_on_disk(tmp_path: Path):
    """Absence must be reportable, not guessed at."""
    root = tmp_path / "slug"
    root.mkdir()
    assert run_meta.run_start(root) == ("", "")


# ---------------------------------------------------------------------------
# active_time


def test_sums_gaps_under_the_threshold():
    stamps = [
        "2026-08-21T16:00:00Z",
        "2026-08-21T16:10:00Z",  # 600s
        "2026-08-21T16:15:00Z",  # 300s
    ]
    hours, excluded, largest = run_meta.active_time(stamps, idle_gap=1800)
    assert hours == pytest.approx(900 / 3600)
    assert excluded == 0
    assert largest == 0.0


def test_excludes_idle_gap_and_reports_it():
    """The overnight break between sittings is what makes span useless."""
    stamps = [
        "2026-08-21T16:00:00Z",
        "2026-08-21T16:05:00Z",  # 300s, counted
        "2026-08-23T18:00:00Z",  # ~50h, excluded
        "2026-08-23T18:02:00Z",  # 120s, counted
    ]
    hours, excluded, largest = run_meta.active_time(stamps, idle_gap=1800)
    assert hours == pytest.approx(420 / 3600)
    assert excluded == 1
    assert largest > 40 * 3600


def test_threshold_is_insensitive_across_the_measured_band():
    """A real run's largest working gap was 14.7min and its next gap 48.5h, so
    every threshold in between must agree. A number that moves with the knob
    would not be worth printing."""
    stamps = [
        "2026-08-21T16:00:00Z",
        "2026-08-21T16:14:42Z",  # 882s — a slow subagent, still work
        "2026-08-23T16:00:00Z",  # overnight
    ]
    answers = {run_meta.active_time(stamps, idle_gap=t)[0] for t in (900, 1800, 3600)}
    assert len(answers) == 1


def test_too_few_stamps_yields_zero_not_a_guess():
    assert run_meta.active_time([]) == (0.0, 0, 0.0)
    assert run_meta.active_time(["2026-08-21T16:00:00Z"]) == (0.0, 0, 0.0)


def test_unparseable_stamps_are_skipped_not_fatal():
    stamps = ["nonsense", "2026-08-21T16:00:00Z", "2026-08-21T16:01:00Z"]
    hours, excluded, _ = run_meta.active_time(stamps)
    assert hours == pytest.approx(60 / 3600)
    assert excluded == 0


def test_stamps_are_sorted_before_differencing():
    """Records arrive per-file, so across two transcripts they are not ordered."""
    ordered = ["2026-08-21T16:00:00Z", "2026-08-21T16:01:00Z"]
    assert run_meta.active_time(ordered) == run_meta.active_time(ordered[::-1])


def test_active_time_flows_through_read_tokens(proj: Path):
    (proj / "s.jsonl").write_text(
        "\n".join(
            [
                _record(
                    "2026-08-21T16:00:00Z",
                    usage={"output_tokens": 1},
                    rtype="assistant",
                ),
                _record(
                    "2026-08-21T16:00:30Z",
                    usage={"output_tokens": 1},
                    rtype="assistant",
                ),
            ]
        )
    )
    stats = run_meta.read_tokens(proj)
    hours, _, _ = run_meta.active_time(stats.stamps)
    assert hours == pytest.approx(30 / 3600)


def test_since_excludes_earlier_sessions(proj: Path):
    """The bug this whole change exists for: unrelated sessions in the same
    project directory must not be counted as part of this run."""
    (proj / "old.jsonl").write_text(
        _record("2026-08-14T09:00:00Z", usage={"output_tokens": 999}, rtype="assistant")
    )
    (proj / "new.jsonl").write_text(
        _record("2026-08-21T16:30:00Z", usage={"output_tokens": 5}, rtype="assistant")
    )
    assert run_meta.read_tokens(proj).totals["output_tokens"] == 1004
    scoped = run_meta.read_tokens(proj, since="2026-08-21T16:03:16Z")
    assert scoped.totals["output_tokens"] == 5
