# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for scripts/multi_search.py."""

import io
import json
import sys
from contextlib import redirect_stdout
from unittest.mock import MagicMock, patch

import pytest

from scripts import multi_search

# ---------------------------------------------------------------------------
# deduplicate()
# ---------------------------------------------------------------------------


class TestDeduplicate:
    def test_empty_input_returns_empty(self):
        assert multi_search.deduplicate([]) == []

    def test_keeps_first_occurrence_of_duplicate_url(self):
        results = [
            {
                "url": "https://a.example",
                "title": "first",
                "snippet": "",
                "engine": "ddg",
            },
            {
                "url": "https://a.example",
                "title": "second",
                "snippet": "",
                "engine": "ddg",
            },
        ]
        deduped = multi_search.deduplicate(results)
        assert len(deduped) == 1
        assert deduped[0]["title"] == "first"

    def test_preserves_order(self):
        results = [
            {"url": "https://a.example", "title": "a", "snippet": "", "engine": "ddg"},
            {"url": "https://b.example", "title": "b", "snippet": "", "engine": "ddg"},
            {"url": "https://c.example", "title": "c", "snippet": "", "engine": "ddg"},
        ]
        deduped = multi_search.deduplicate(results)
        assert [r["url"] for r in deduped] == [
            "https://a.example",
            "https://b.example",
            "https://c.example",
        ]

    def test_drops_entries_with_empty_url(self):
        results = [
            {"url": "", "title": "no url", "snippet": "", "engine": "ddg"},
            {"url": "https://a.example", "title": "ok", "snippet": "", "engine": "ddg"},
        ]
        deduped = multi_search.deduplicate(results)
        assert len(deduped) == 1
        assert deduped[0]["url"] == "https://a.example"


# ---------------------------------------------------------------------------
# search_ddg() — DDGS mocked
# ---------------------------------------------------------------------------


class TestSearchDdg:
    def test_normalizes_ddgs_response(self):
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.return_value = [
            {"href": "https://a.example", "title": "Title A", "body": "Body A"},
            {"href": "https://b.example", "title": "Title B", "body": "Body B"},
        ]
        with patch.dict(
            "sys.modules",
            {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)},
        ):
            results = multi_search.search_ddg("anything", limit=2)

        assert results == [
            {
                "url": "https://a.example",
                "title": "Title A",
                "snippet": "Body A",
                "engine": "ddg",
            },
            {
                "url": "https://b.example",
                "title": "Title B",
                "snippet": "Body B",
                "engine": "ddg",
            },
        ]

    def test_handles_missing_fields(self):
        fake_ddgs = MagicMock()
        fake_ddgs.__enter__.return_value.text.return_value = [{}]
        with patch.dict(
            "sys.modules",
            {"ddgs": MagicMock(DDGS=lambda: fake_ddgs)},
        ):
            results = multi_search.search_ddg("anything", limit=1)

        assert results == [{"url": "", "title": "", "snippet": "", "engine": "ddg"}]

    def test_missing_dependency_exits_with_error(self, capsys):
        with patch.dict("sys.modules", {"ddgs": None}):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.search_ddg("anything", limit=1)
        assert excinfo.value.code == 1
        assert "ddgs not installed" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# main() — argparse + JSON contract
# ---------------------------------------------------------------------------


class TestMain:
    def _run_main(self, argv: list[str]) -> str:
        buf = io.StringIO()
        with patch.object(sys, "argv", ["multi_search", *argv]):
            with redirect_stdout(buf):
                multi_search.main()
        return buf.getvalue()

    def test_unknown_engine_exits_nonzero(self, capsys):
        with patch.object(
            sys, "argv", ["multi_search", "--query", "x", "--engines", "bing"]
        ):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.main()
        assert excinfo.value.code == 1
        err = capsys.readouterr().err
        assert "unknown engine" in err
        assert "bing" in err

    def test_missing_query_arg_errors(self):
        with patch.object(sys, "argv", ["multi_search"]):
            with pytest.raises(SystemExit) as excinfo:
                multi_search.main()
        # argparse exits with 2 on missing required args
        assert excinfo.value.code == 2

    def test_outputs_dedup_json(self):
        with patch.object(
            multi_search,
            "ENGINE_FUNCTIONS",
            {
                "ddg": lambda q, limit: [
                    {
                        "url": "https://a.example",
                        "title": "a",
                        "snippet": "",
                        "engine": "ddg",
                    },
                    {
                        "url": "https://a.example",
                        "title": "dup",
                        "snippet": "",
                        "engine": "ddg",
                    },
                ]
            },
        ):
            output = self._run_main(
                ["--query", "x", "--engines", "ddg", "--limit", "5"]
            )

        parsed = json.loads(output)
        assert len(parsed) == 1
        assert parsed[0]["url"] == "https://a.example"
        assert parsed[0]["title"] == "a"

    def test_engine_failure_warns_but_does_not_exit(self, capsys):
        def failing(_query, _limit):
            raise RuntimeError("network down")

        with patch.object(multi_search, "ENGINE_FUNCTIONS", {"ddg": failing}):
            output = self._run_main(["--query", "x"])

        assert json.loads(output) == []
        assert "ddg search failed" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# Live smoke test — opt-in (`make test-live`)
# ---------------------------------------------------------------------------


@pytest.mark.live
def test_live_ddg_returns_results():
    """Sanity check that the DDGS shape we depend on is unchanged."""
    results = multi_search.search_ddg("python programming language", limit=3)
    assert len(results) >= 1
    first = results[0]
    assert first["url"].startswith("http")
    assert first["engine"] == "ddg"
    assert isinstance(first["title"], str)
    assert isinstance(first["snippet"], str)
