# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for scripts/put_data.py and scripts/reap_data.py."""

import io
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from scripts import _data_paths, put_data, reap_data


@pytest.fixture
def data_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect DATA_ROOT into tmp_path so tests never touch ~/.claude/."""
    monkeypatch.setattr(_data_paths, "DATA_ROOT", tmp_path)
    return tmp_path


def _run_put(argv: list[str], stdin_text: str) -> None:
    with patch.object(sys, "argv", ["put_data", *argv]):
        with patch.object(sys, "stdin", io.StringIO(stdin_text)):
            put_data.main()


def _run_reap(argv: list[str]) -> None:
    with patch.object(sys, "argv", ["reap_data", *argv]):
        reap_data.main()


# ---------------------------------------------------------------------------
# _data_paths.validate_slug
# ---------------------------------------------------------------------------


class TestValidateSlug:
    @pytest.mark.parametrize(
        "slug",
        [
            "",
            "has/slash",
            "has\\slash",
            "..",
            "../escape",
            ".hidden",
            "a/../b",
            "$HOME",
            "${HOME}",
            "%USERPROFILE%",
            "~",
            "~user",
            "has space",
            "UPPERCASE",
            "Topic-Mixed",
            "-leading-dash",
            "trailing-dash-",
            "double--dash",
            "with.period",
            "with`backtick",
            "with'quote",
            'with"dquote',
            "semi;colon",
            "pipe|char",
        ],
    )
    def test_rejects_invalid_slug(self, slug, capsys):
        with pytest.raises(SystemExit) as excinfo:
            _data_paths.validate_slug(slug)
        assert excinfo.value.code == 1
        assert "invalid slug" in capsys.readouterr().err

    @pytest.mark.parametrize(
        "slug", ["queue-system", "clarinet-vs-french-horn", "otel-v2", "a"]
    )
    def test_accepts_kebab_case(self, slug):
        _data_paths.validate_slug(slug)  # no exception


# ---------------------------------------------------------------------------
# _data_paths.safe_target
# ---------------------------------------------------------------------------


class TestSafeTarget:
    def test_rejects_absolute_relative_path(self, data_root, capsys):
        with pytest.raises(SystemExit) as excinfo:
            _data_paths.safe_target("topic", "/etc/passwd")
        assert excinfo.value.code == 1
        assert "invalid relative path" in capsys.readouterr().err

    def test_rejects_dotdot_escape(self, data_root, capsys):
        with pytest.raises(SystemExit) as excinfo:
            _data_paths.safe_target("topic", "../../etc/passwd")
        assert excinfo.value.code == 1
        assert "invalid relative path" in capsys.readouterr().err

    def test_accepts_nested_relative(self, data_root):
        result = _data_paths.safe_target("topic", "fetched/page-1.md")
        assert result == data_root / "topic" / "fetched" / "page-1.md"


# ---------------------------------------------------------------------------
# put_data.main
# ---------------------------------------------------------------------------


class TestPutData:
    def test_writes_stdin_verbatim(self, data_root, capsys):
        content = "# Fetched: https://example.test\n\nRaw body content.\n"
        _run_put(["topic-a", "page.md"], content)
        target = data_root / "topic-a" / "page.md"
        assert target.read_text(encoding="utf-8") == content
        assert str(target) in capsys.readouterr().out

    def test_creates_parent_directories(self, data_root):
        _run_put(["topic-b", "deep/nested/file.md"], "x")
        assert (data_root / "topic-b" / "deep" / "nested" / "file.md").exists()

    def test_missing_args_exits_with_usage_error(self, capsys):
        with patch.object(sys, "argv", ["put_data", "only-one-arg"]):
            with pytest.raises(SystemExit) as excinfo:
                put_data.main()
        assert excinfo.value.code == 2
        assert "Usage:" in capsys.readouterr().err

    def test_path_escape_rejected(self, data_root, capsys):
        with pytest.raises(SystemExit) as excinfo:
            _run_put(["topic-c", "../outside.md"], "oops")
        assert excinfo.value.code == 1
        assert "invalid relative path" in capsys.readouterr().err

    def test_overwrite_replaces_content(self, data_root):
        _run_put(["topic-d", "page.md"], "first")
        _run_put(["topic-d", "page.md"], "second")
        assert (data_root / "topic-d" / "page.md").read_text(
            encoding="utf-8"
        ) == "second"

    def test_atomic_write_leaves_target_untouched_on_failure(
        self, data_root, capsys, monkeypatch
    ):
        """If the rename fails, the existing target must be preserved."""
        target_dir = data_root / "topic-f"
        target_dir.mkdir()
        target = target_dir / "page.md"
        target.write_text("original", encoding="utf-8")

        def _boom(self, _other):
            raise OSError("simulated rename failure")

        monkeypatch.setattr(Path, "replace", _boom)

        with pytest.raises(SystemExit) as excinfo:
            _run_put(["topic-f", "page.md"], "new content that should not land")
        assert excinfo.value.code == 1
        assert "Error writing" in capsys.readouterr().err
        assert target.read_text(encoding="utf-8") == "original"

    def test_tempfile_cleaned_up_on_failure(self, data_root, monkeypatch):
        """No .part debris left behind when the rename fails."""
        target_dir = data_root / "topic-g"
        target_dir.mkdir()

        def _boom(self, _other):
            raise OSError("simulated rename failure")

        monkeypatch.setattr(Path, "replace", _boom)

        with pytest.raises(SystemExit):
            _run_put(["topic-g", "page.md"], "content")

        # no leftover .part files
        leftovers = list(target_dir.iterdir())
        assert leftovers == [], f"tempfile debris: {leftovers}"


# ---------------------------------------------------------------------------
# reap_data.main
# ---------------------------------------------------------------------------


class TestReapData:
    def test_removes_existing_slug_tree(self, data_root):
        (data_root / "topic-e").mkdir()
        (data_root / "topic-e" / "file.md").write_text("hi", encoding="utf-8")
        _run_reap(["topic-e"])
        assert not (data_root / "topic-e").exists()

    def test_idempotent_on_missing_slug(self, data_root):
        _run_reap(["never-existed"])  # should not raise

    def test_rejects_invalid_slug(self, capsys):
        with patch.object(sys, "argv", ["reap_data", "../danger"]):
            with pytest.raises(SystemExit) as excinfo:
                reap_data.main()
        assert excinfo.value.code == 1
        assert "invalid slug" in capsys.readouterr().err

    def test_missing_args_exits_with_usage_error(self, capsys):
        with patch.object(sys, "argv", ["reap_data"]):
            with pytest.raises(SystemExit) as excinfo:
                reap_data.main()
        assert excinfo.value.code == 2
        assert "Usage:" in capsys.readouterr().err

    def test_only_removes_named_slug(self, data_root):
        (data_root / "keep-me").mkdir()
        (data_root / "reap-me").mkdir()
        _run_reap(["reap-me"])
        assert (data_root / "keep-me").exists()
        assert not (data_root / "reap-me").exists()
