# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Shared helpers for the cited-research data wrappers.

DATA_ROOT is the single location on disk where the skill persists transient
research artifacts (fetched page content, agent hand-off files). The skill
never writes directly — `put_data.py` and `reap_data.py` are the only
entry points, so a single allowlisted Bash rule per script covers every
write and every cleanup.
"""

import re
import sys
from pathlib import Path

DATA_ROOT = Path.home() / ".local" / "share" / "cited-research-data"

# Kebab-case lowercase alphanumerics. Matches what SKILL.md specifies for
# topic slugs. Rejects path separators, env-var markers (`$`, `%`), tilde,
# quotes, spaces, shell metacharacters, hidden-file leaders, and traversal
# sequences — all of which would either escape DATA_ROOT after expansion
# or break the kebab-case contract.
_SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def validate_slug(slug: str) -> None:
    """Reject slugs that could escape DATA_ROOT or break the slug contract."""
    if not _SLUG_PATTERN.match(slug):
        print(
            f"Error: invalid slug: {slug!r} "
            "(expected kebab-case lowercase alphanumerics)",
            file=sys.stderr,
        )
        sys.exit(1)


def safe_target(slug: str, rel: str) -> Path:
    """Resolve `<slug>/<rel>` under DATA_ROOT, refusing any escape."""
    validate_slug(slug)
    rel_path = Path(rel)
    # `is_absolute()` is platform-dependent (on Windows, "/etc" is not absolute),
    # so also reject any leading path separator explicitly.
    if (
        rel_path.is_absolute()
        or rel.startswith("/")
        or rel.startswith("\\")
        or any(p == ".." for p in rel_path.parts)
    ):
        print(f"Error: invalid relative path: {rel}", file=sys.stderr)
        sys.exit(1)
    return DATA_ROOT / slug / rel_path
