# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Shared helpers for the cited-research data wrappers.

DATA_ROOT is the per-project working directory where the skill persists
transient research artifacts (fetched page content, agent hand-off files).
It resolves to `./.tmp-cited-research/` relative to the process working
directory — i.e., colocated with the user's project rather than orphaned
in a user-global cache. `bootstrap_tmp.sh` provisions the parent and its
`.gitignore`. `put_data.py` and `reap_data.py` are the only write/cleanup
entry points, so a single allowlisted Bash rule per script covers every
mutation.
"""

import re
import sys
import tempfile
from pathlib import Path

DATA_ROOT = Path.cwd() / ".tmp-cited-research"

# Kebab-case lowercase alphanumerics. Matches what SKILL.md specifies for
# topic slugs. Rejects path separators, env-var markers (`$`, `%`), tilde,
# quotes, spaces, shell metacharacters, hidden-file leaders, and traversal
# sequences — all of which would either escape DATA_ROOT after expansion
# or break the kebab-case contract.
_SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def validate_slug(slug: str) -> None:
    """Reject slugs that could escape DATA_ROOT or break the slug contract."""
    if not _SLUG_PATTERN.match(slug):
        print(
            f"Error: invalid slug: {slug!r} "
            "(expected kebab-case lowercase alphanumerics)",
            file=sys.stderr,
        )
        sys.exit(1)


def require_slug_root(slug: str) -> Path:
    """Return the slug root, exiting 1 if bootstrap_tmp.sh has not run.

    Auto-creating the slug root would bypass the parent `.gitignore` that
    bootstrap installs, risking fetched URLs leaking into a commit.
    """
    slug_root = DATA_ROOT / slug
    if not slug_root.is_dir():
        print(
            f"Error: slug root does not exist: {slug_root}. "
            f"Run scripts/bootstrap_tmp.sh {slug} first.",
            file=sys.stderr,
        )
        sys.exit(1)
    return slug_root


def atomic_write(target: Path, content: str) -> None:
    """Write `content` to `target` atomically, creating parent dirs.

    Streams to a sibling tempfile then renames into place, so either the
    whole content lands at `target` or `target` is unchanged — audit agents
    never read a half-written file. The tempfile is cleaned up on any
    OSError so no `.part` debris accumulates.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".part",
            delete=False,
        ) as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)
        tmp_path.replace(target)
    except OSError as e:
        if tmp_path is not None:
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass
        print(f"Error writing {target}: {e}", file=sys.stderr)
        sys.exit(1)


def safe_target(slug: str, rel: str) -> Path:
    """Resolve `<slug>/<rel>` under DATA_ROOT, refusing any escape."""
    validate_slug(slug)
    rel_path = Path(rel)
    # `is_absolute()` is platform-dependent (on Windows, "/etc" is not absolute),
    # so also reject any leading path separator explicitly.
    if (
        rel_path.is_absolute()
        or rel.startswith("/")
        or rel.startswith("\\")
        or any(p == ".." for p in rel_path.parts)
    ):
        print(f"Error: invalid relative path: {rel}", file=sys.stderr)
        sys.exit(1)
    return DATA_ROOT / slug / rel_path
