#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7 (1M context))
#
# Bootstrap the per-slug workspace under ./.tmp-cited-research/.
#
# WIPES ./.tmp-cited-research/<slug>/ on every invocation so each research
# run on a given topic starts from a clean slate. Other topic slugs in the
# same parent directory are untouched (per-slug isolation).
#
# Ensures the parent ./.tmp-cited-research/ exists and contains a .gitignore
# of '*' so nothing inside is accidentally committed. Idempotent — the
# .gitignore is overwritten to the same value, so repeated invocations are
# safe.
#
# Usage:
#     bootstrap_tmp.sh <slug>
#
# Honors PROJECT_ROOT env var when set (used by tests); defaults to PWD.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: bootstrap_tmp.sh <slug>" >&2
    exit 2
fi

SLUG="$1"

# Slug must match the kebab-case contract enforced by scripts/_data_paths.py:
# lowercase alphanumerics in segments joined by single hyphens, no leading
# or trailing dash, no double-dash, no path separators or shell metacharacters.
if ! [[ "$SLUG" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
    echo "error: invalid slug: '$SLUG' (expected kebab-case lowercase alphanumerics)" >&2
    exit 1
fi

ROOT="${PROJECT_ROOT:-$PWD}"
PARENT="$ROOT/.tmp-cited-research"
WORK_DIR="$PARENT/$SLUG"

mkdir -p "$PARENT"

# Idempotent .gitignore: bare '*' with no trailing newline, matching the
# jewzaam-reviews bootstrap-tmp.sh convention.
printf '*' > "$PARENT/.gitignore"

# Per-slug wipe and recreate. Only this slug's subtree is removed; sibling
# slugs in the same parent remain intact.
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"

# Record the run's start time. run_report.py scopes token accounting to this
# bound; without it the report spans every session that ever ran in the same
# project directory, because /clear starts a new conversation but not a new
# project directory. Recorded rather than inferred: the directory's own birth
# time would be exact, but CPython on Linux does not expose st_birthtime, and
# the earliest artifact lands minutes late — late enough to drop the first
# agents dispatched.
date -u +%Y-%m-%dT%H:%M:%S.%3NZ > "$WORK_DIR/started"

echo "bootstrap_tmp: $WORK_DIR ready (wiped)"
