# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Fetch a URL through the host-side fetch service and persist it.

A sandbox cannot make HTTPS requests to arbitrary hosts: its only egress is
OpenShell's HTTP CONNECT proxy, which permits only hosts named in the
sandbox network policy. Research follows links discovered at runtime, so the
hosts are not knowable in advance. The fetch service runs on the host,
outside the sandbox, and performs the request on the sandbox's behalf over
plain HTTP — the sandbox never speaks TLS and never issues a CONNECT.

This script is the coordinator's single entry point for reading a known URL.
It combines the service call with persistence under
`./.tmp-cited-research/<slug>/`, so one allowlisted Bash rule covers every
fetch and the fetched-file header format stays consistent.

Usage:
    python fetch_url.py <slug> <relative-path> <url>
    python fetch_url.py --check

Encyclopedia handling: when the URL is a Wikipedia or Grokipedia article,
the outbound citation links are extracted and written to a
`<relative-path>.refs` sidecar, one URL per line. Those are the sources to
fetch and cite; the article itself is tertiary. This is plain parsing, done
here so no caller has to be told to do it.

The service address defaults to http://172.30.0.21:8090 and is overridable
via the CITED_RESEARCH_FETCH_SERVICE environment variable.

Exit codes:
    0  a file was written — either the page (Status: OK) or a recorded
       failure (Status: FAILED), which agents must still see
    1  write error, or a malformed request the service rejected
    2  usage error
    3  the service is unreachable, or the sandbox network policy blocks it.
       The operator must act; there is no alternative egress to route to.
"""

import argparse
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser

from scripts._data_paths import atomic_write, require_slug_root, safe_target

DEFAULT_SERVICE = "http://172.30.0.21:8090"

# The service caps responses at 8 MB and upstream reads at 30 s. Allow
# headroom past its own timeout so a slow upstream surfaces as the service's
# own `502 upstream error:` rather than a client-side timeout here, which
# would be indistinguishable from the service being down.
TIMEOUT_SECONDS = 45

OFFLINE_MESSAGE = (
    "The fetch service is not reachable at {addr}, so I cannot read web "
    "pages. Start it with:  sandbox.sh --fetch-service"
)

POLICY_MESSAGE = (
    "The fetch service address {addr} is refused by the sandbox network "
    "policy (OpenShell proxy, not the service). The policy must name that "
    "host and port."
)

# Tags whose character data is markup machinery, never page prose.
_SKIP_TAGS = {"script", "style", "noscript", "head", "template", "svg"}

# Tags that imply a line break in the extracted text.
_BREAK_TAGS = {
    "p",
    "br",
    "div",
    "tr",
    "li",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "section",
    "article",
    "table",
    "blockquote",
}


# Hosts whose pages are mined for their reference lists rather than cited.
# Matched as domain suffixes so any language subdomain qualifies.
ENCYCLOPEDIA_HOSTS = ("wikipedia.org", "grokipedia.com")

# Infrastructure links that appear on every encyclopedia page and are never
# the citation being sought.
_REF_HOST_DENYLIST = (
    "wikimedia.org",
    "wikidata.org",
    "mediawiki.org",
    "wikibooks.org",
    "wikiquote.org",
    "wikisource.org",
    "wiktionary.org",
    "wikiversity.org",
    "wikivoyage.org",
    "creativecommons.org",
    "archive.org/web",
    "x.com",
    "twitter.com",
)


def is_encyclopedia(url: str) -> bool:
    """True when a URL points at a reference work we mine instead of cite."""
    host = urllib.parse.urlparse(url).netloc.lower()
    return any(host == h or host.endswith("." + h) for h in ENCYCLOPEDIA_HOSTS)


class _RefExtractor(HTMLParser):
    """Collect outbound citation links from an encyclopedia article.

    Deterministic, not a judgement call: MediaWiki marks every outbound link
    with a class containing "external", which is exactly the reference list
    plus the external-links section. Where that marker is absent (Grokipedia
    and other non-MediaWiki sites), fall back to any absolute cross-host
    link. Infrastructure hosts are filtered because they appear on every
    page and are never the source being cited.
    """

    def __init__(self, page_host: str) -> None:
        super().__init__(convert_charrefs=True)
        self.page_host = page_host
        self.marked: list[str] = []
        self.unmarked: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        d = dict(attrs)
        href = (d.get("href") or "").strip()
        if not href.startswith(("http://", "https://")):
            return
        host = urllib.parse.urlparse(href).netloc.lower()
        if not host or host == self.page_host:
            return
        if any(bad in href for bad in _REF_HOST_DENYLIST):
            return
        if "external" in (d.get("class") or ""):
            self.marked.append(href)
        else:
            self.unmarked.append(href)

    def urls(self) -> list[str]:
        chosen = self.marked or self.unmarked
        seen, out = set(), []
        for u in chosen:
            if u not in seen:
                seen.add(u)
                out.append(u)
        return out


def extract_reference_urls(html: str, page_url: str) -> list[str]:
    """Return deduplicated outbound citation URLs from an article."""
    host = urllib.parse.urlparse(page_url).netloc.lower()
    parser = _RefExtractor(host)
    try:
        parser.feed(html)
        parser.close()
    except Exception:
        return []
    return parser.urls()


class _TextExtractor(HTMLParser):
    """Collapse HTML into readable text, preserving absolute link targets.

    Link hrefs are kept inline as `text (url)` because research agents are
    asked to report follow-up URLs found inside fetched content — stripping
    anchors would silently remove that signal.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._parts: list[str] = []
        self._skip_depth = 0
        self._href: str | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in _SKIP_TAGS:
            self._skip_depth += 1
            return
        if tag in _BREAK_TAGS:
            self._parts.append("\n")
        if tag == "a":
            href = dict(attrs).get("href") or ""
            self._href = href if href.startswith(("http://", "https://")) else None

    def handle_endtag(self, tag: str) -> None:
        if tag in _SKIP_TAGS:
            self._skip_depth = max(0, self._skip_depth - 1)
            return
        if tag == "a" and self._href:
            self._parts.append(f" ({self._href})")
            self._href = None
        if tag in _BREAK_TAGS:
            self._parts.append("\n")

    def handle_data(self, data: str) -> None:
        if self._skip_depth == 0 and data.strip():
            self._parts.append(data.strip() + " ")

    def text(self) -> str:
        joined = "".join(self._parts)
        # Collapse runs of blank lines so the output stays scannable.
        lines = [line.strip() for line in joined.splitlines()]
        out: list[str] = []
        for line in lines:
            if line or (out and out[-1]):
                out.append(line)
        return "\n".join(out).strip()


def html_to_text(html: str) -> str:
    """Extract readable text from HTML, tolerating malformed markup."""
    parser = _TextExtractor()
    try:
        parser.feed(html)
        parser.close()
    except Exception:
        # A parse failure must not lose the page. Fall back to raw markup
        # rather than writing an empty file that reads as "source had no
        # content" to an audit agent.
        return html
    return parser.text()


def _service_base() -> str:
    return os.environ.get("CITED_RESEARCH_FETCH_SERVICE", DEFAULT_SERVICE).rstrip("/")


def check_service() -> int:
    """Probe /healthz. Returns a process exit code."""
    base = _service_base()
    try:
        with urllib.request.urlopen(f"{base}/healthz", timeout=10) as resp:
            if resp.status == 200:
                print(f"fetch service OK: {base}")
                return 0
            print(f"fetch service unhealthy: HTTP {resp.status}", file=sys.stderr)
            return 3
    except urllib.error.HTTPError as e:
        body = _read_error_body(e)
        print(_classify_denial(e.code, body, base), file=sys.stderr)
        return 3
    except (urllib.error.URLError, OSError) as e:
        print(OFFLINE_MESSAGE.format(addr=base), file=sys.stderr)
        print(f"({e})", file=sys.stderr)
        return 3


def _one_line(text: str, limit: int = 120) -> str:
    """Collapse whitespace and truncate, keeping a value header-safe."""
    return " ".join(text.split())[:limit]


def _read_error_body(e: urllib.error.HTTPError) -> str:
    try:
        return e.read().decode("utf-8", errors="replace")
    except Exception:
        return ""


# Markers OpenShell's proxy puts in its own denial body. Anything else at
# 403 came from the service or the upstream site, not the proxy.
_PROXY_DENIAL_MARKERS = ("policy_denied", "not permitted by policy")


def is_proxy_denial(status: int, body: str) -> bool:
    """True only when a 403 came from OpenShell's proxy.

    Three different things answer 403 and they need opposite handling:
    the proxy denying the service address (fatal, operator must act), the
    service declining a URL (`refused:`, recoverable), and the upstream
    site blocking the request (bot protection, very common, recoverable).
    Matching the proxy's own marker rather than treating every unfamiliar
    403 as fatal keeps a routine Cloudflare block from aborting a run.
    """
    if status != 403:
        return False
    lowered = body.lower()
    return any(marker in lowered for marker in _PROXY_DENIAL_MARKERS)


def _classify_denial(status: int, body: str, base: str) -> str:
    if is_proxy_denial(status, body):
        return POLICY_MESSAGE.format(addr=base)
    return f"fetch service returned HTTP {status}: {_one_line(body, 200)}"


def fetch(url: str) -> tuple[str, str, str]:
    """Fetch `url` via the service.

    Returns (status_line, content_type, body) where status_line is the value
    for the file's `# Status:` header. Raises SystemExit(3) when the service
    or the policy — rather than the upstream page — is the problem.
    """
    base = _service_base()
    encoded = urllib.parse.quote(url, safe="")
    request_url = f"{base}/fetch?url={encoded}"
    try:
        with urllib.request.urlopen(request_url, timeout=TIMEOUT_SECONDS) as resp:
            raw = resp.read()
            ctype = resp.headers.get("Content-Type", "")
            return "OK", ctype, raw.decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        body = _read_error_body(e)
        stripped = body.lstrip()
        if is_proxy_denial(e.code, body):
            print(POLICY_MESSAGE.format(addr=base), file=sys.stderr)
            raise SystemExit(3)
        if e.code in (400, 405):
            print(f"Error: bad request to fetch service: {body[:200]}", file=sys.stderr)
            raise SystemExit(1)
        # 403 `refused:`, 502 `upstream error:`, and upstream statuses such
        # as 404 are all page-level failures. Record them and continue —
        # a 20-30% inaccessibility rate is expected, not exceptional.
        #
        # Collapse whitespace before truncating: error bodies are often full
        # HTML error pages, and an embedded newline would split the single-line
        # `# Status:` header and spill markup into the header block.
        return f"FAILED ({e.code}: {_one_line(stripped)})", "", ""
    except (urllib.error.URLError, OSError) as e:
        print(OFFLINE_MESSAGE.format(addr=base), file=sys.stderr)
        print(f"({e})", file=sys.stderr)
        raise SystemExit(3)


def render(url: str, status: str, ctype: str, body: str) -> str:
    """Build the fetched-file content, header included."""
    lowered = ctype.lower()
    if status == "OK":
        if "html" in lowered:
            body = html_to_text(body)
        elif lowered and not lowered.startswith(("text/", "application/json")):
            status = f"FAILED (binary content-type {ctype}, not extractable as text)"
            body = ""
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # `# Status:` must stay one line — agents and the audit step read the
    # header as a fixed three-line block.
    return (
        f"# Fetched: {url}\n"
        f"# Date: {stamp}\n"
        f"# Status: {_one_line(status, 200)}\n\n"
        f"{body}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch a URL via the host-side fetch service and persist it."
    )
    parser.add_argument("--check", action="store_true", help="probe /healthz and exit")
    parser.add_argument("slug", nargs="?", help="topic slug")
    parser.add_argument("rel", nargs="?", help="relative path within the slug dir")
    parser.add_argument("url", nargs="?", help="URL to fetch")
    args = parser.parse_args()

    if args.check:
        sys.exit(check_service())
    if not (args.slug and args.rel and args.url):
        parser.error("slug, relative-path, and url are required unless --check")

    target = safe_target(args.slug, args.rel)
    require_slug_root(args.slug)
    status, ctype, body = fetch(args.url)
    atomic_write(target, render(args.url, status, ctype, body))

    # Encyclopedia articles are mined, not cited. Harvesting their reference
    # lists is deterministic parsing, so it happens here rather than being
    # asked of a model: the sidecar is a plain URL-per-line file the caller
    # feeds straight back into the fetch queue.
    refs_note = ""
    if status == "OK" and "html" in ctype.lower() and is_encyclopedia(args.url):
        refs = extract_reference_urls(body, args.url)
        if refs:
            refs_target = safe_target(args.slug, args.rel + ".refs")
            atomic_write(refs_target, "\n".join(refs) + "\n")
            refs_note = f"\t{len(refs)} refs -> {refs_target}"

    print(f"{status}\t{target}{refs_note}")


if __name__ == "__main__":
    main()
