# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Fetch a URL through the host-side fetch service and persist it.

A sandbox cannot make HTTPS requests to arbitrary hosts: its only egress is
OpenShell's HTTP CONNECT proxy, which permits only hosts named in the
sandbox network policy. Research follows links discovered at runtime, so the
hosts are not knowable in advance. The fetch service runs on the host,
outside the sandbox, and performs the request on the sandbox's behalf over
plain HTTP — the sandbox never speaks TLS and never issues a CONNECT.

This script is the coordinator's single entry point for reading a known URL.
It combines the service call with persistence under
`./.tmp-cited-research/<slug>/`, so one allowlisted Bash rule covers every
fetch and the fetched-file header format stays consistent.

Usage:
    python fetch_url.py <slug> <relative-path> <url>
    python fetch_url.py --batch <slug>      # URLs on stdin, one per line
    python fetch_url.py --check

Encyclopedia handling: when the URL is a Wikipedia or Grokipedia article,
the outbound citation links are extracted and written to a
`<relative-path>.refs` sidecar, one URL per line. Those are the sources to
fetch and cite; the article itself is tertiary. This is plain parsing, done
here so no caller has to be told to do it.

The service address defaults to http://172.30.0.21:8090 and is overridable
via the CITED_RESEARCH_FETCH_SERVICE environment variable.

Exit codes:
    0  a file was written — either the page (Status: OK) or a recorded
       failure (Status: FAILED), which agents must still see
    1  write error, or a malformed request the service rejected
    2  usage error
    3  the service is unreachable, or the sandbox network policy blocks it.
       The operator must act; there is no alternative egress to route to.
"""

import argparse
import hashlib
import io
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser

from scripts._data_paths import atomic_write, require_slug_root, safe_target

DEFAULT_SERVICE = "http://172.30.0.21:8090"

# Pages of a PDF to extract. A 900-page gazette would otherwise blow up an
# agent's context while presenting itself as a complete source.
MAX_PDF_PAGES = 400

# OCR runs about 4 s per page on CPU, so the cap is two orders of magnitude
# tighter than the text-layer one. 20 pages is roughly 90 s — tolerable inside
# a batch; 400 would be half an hour for one document.
MAX_OCR_PAGES = 20

# Below this, an `OK` HTML fetch is treated as a failure. A JS-rendered page
# returns its shell — nav, footer, a loading div — and nothing else. Recording
# that as a success is worse than a clean failure: it grades as a fetched
# source and supports no claim made on the page.
MIN_HTML_CHARS = 200

# The service caps responses at 8 MB and upstream reads at 30 s. Allow
# headroom past its own timeout so a slow upstream surfaces as the service's
# own `502 upstream error:` rather than a client-side timeout here, which
# would be indistinguishable from the service being down.
TIMEOUT_SECONDS = 45

OFFLINE_MESSAGE = (
    "The fetch service is not reachable at {addr}, so I cannot read web "
    "pages. Start it with:  sandbox.sh --fetch-service"
)

POLICY_MESSAGE = (
    "The fetch service address {addr} is refused by the sandbox network "
    "policy (OpenShell proxy, not the service). The policy must name that "
    "host and port."
)

# Tags whose character data is markup machinery, never page prose.
_SKIP_TAGS = {"script", "style", "noscript", "head", "template", "svg"}

# Tags that imply a line break in the extracted text.
_BREAK_TAGS = {
    "p",
    "br",
    "div",
    "tr",
    "li",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "section",
    "article",
    "table",
    "blockquote",
}


# Hosts whose pages are mined for their reference lists rather than cited.
# Matched as domain suffixes so any language subdomain qualifies.
ENCYCLOPEDIA_HOSTS = ("wikipedia.org", "grokipedia.com")

# Infrastructure links that appear on every encyclopedia page and are never
# the citation being sought.
_REF_HOST_DENYLIST = (
    "wikimedia.org",
    "wikidata.org",
    "mediawiki.org",
    "wikibooks.org",
    "wikiquote.org",
    "wikisource.org",
    "wiktionary.org",
    "wikiversity.org",
    "wikivoyage.org",
    "creativecommons.org",
    "archive.org/web",
    "x.com",
    "twitter.com",
)


def is_encyclopedia(url: str) -> bool:
    """True when a URL points at a reference work we mine instead of cite."""
    host = urllib.parse.urlparse(url).netloc.lower()
    return any(host == h or host.endswith("." + h) for h in ENCYCLOPEDIA_HOSTS)


class _RefExtractor(HTMLParser):
    """Collect outbound citation links from an encyclopedia article.

    Deterministic, not a judgement call: MediaWiki marks every outbound link
    with a class containing "external", which is exactly the reference list
    plus the external-links section. Where that marker is absent (Grokipedia
    and other non-MediaWiki sites), fall back to any absolute cross-host
    link. Infrastructure hosts are filtered because they appear on every
    page and are never the source being cited.
    """

    def __init__(self, page_host: str) -> None:
        super().__init__(convert_charrefs=True)
        self.page_host = page_host
        self.marked: list[str] = []
        self.unmarked: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        d = dict(attrs)
        href = (d.get("href") or "").strip()
        if not href.startswith(("http://", "https://")):
            return
        host = urllib.parse.urlparse(href).netloc.lower()
        if not host or host == self.page_host:
            return
        if any(bad in href for bad in _REF_HOST_DENYLIST):
            return
        if "external" in (d.get("class") or ""):
            self.marked.append(href)
        else:
            self.unmarked.append(href)

    def urls(self) -> list[str]:
        chosen = self.marked or self.unmarked
        seen, out = set(), []
        for u in chosen:
            if u not in seen:
                seen.add(u)
                out.append(u)
        return out


def extract_reference_urls(html: str, page_url: str) -> list[str]:
    """Return deduplicated outbound citation URLs from an article."""
    host = urllib.parse.urlparse(page_url).netloc.lower()
    parser = _RefExtractor(host)
    try:
        parser.feed(html)
        parser.close()
    except Exception:
        return []
    return parser.urls()


class _TextExtractor(HTMLParser):
    """Collapse HTML into readable text, preserving absolute link targets.

    Link hrefs are kept inline as `text (url)` because research agents are
    asked to report follow-up URLs found inside fetched content — stripping
    anchors would silently remove that signal.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._parts: list[str] = []
        self._skip_depth = 0
        self._href: str | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in _SKIP_TAGS:
            self._skip_depth += 1
            return
        if tag in _BREAK_TAGS:
            self._parts.append("\n")
        if tag == "a":
            href = dict(attrs).get("href") or ""
            self._href = href if href.startswith(("http://", "https://")) else None

    def handle_endtag(self, tag: str) -> None:
        if tag in _SKIP_TAGS:
            self._skip_depth = max(0, self._skip_depth - 1)
            return
        if tag == "a" and self._href:
            self._parts.append(f" ({self._href})")
            self._href = None
        if tag in _BREAK_TAGS:
            self._parts.append("\n")

    def handle_data(self, data: str) -> None:
        if self._skip_depth == 0 and data.strip():
            self._parts.append(data.strip() + " ")

    def text(self) -> str:
        joined = "".join(self._parts)
        # Collapse runs of blank lines so the output stays scannable.
        lines = [line.strip() for line in joined.splitlines()]
        out: list[str] = []
        for line in lines:
            if line or (out and out[-1]):
                out.append(line)
        return "\n".join(out).strip()


def html_to_text(html: str) -> str:
    """Extract readable text from HTML, tolerating malformed markup."""
    parser = _TextExtractor()
    try:
        parser.feed(html)
        parser.close()
    except Exception:
        # A parse failure must not lose the page. Fall back to raw markup
        # rather than writing an empty file that reads as "source had no
        # content" to an audit agent.
        return html
    return parser.text()


def pdf_to_text(raw: bytes) -> tuple[str, str]:
    """Extract a PDF's text layer. Returns (status, text).

    PDFs are not an edge case here: legislation, official gazettes, court
    statistics and intergovernmental reports publish as PDF far more often
    than the commentary that restates them in HTML. Refusing them fails the
    Tier 1 half of a source pool while the Tier 3 restatements succeed.

    A scanned PDF has pages but no text layer, and is reported as its own
    failure rather than as an empty body — an empty body reads to an audit
    agent as "the source said nothing", which is a different and wrong claim.
    """
    try:
        from pypdf import PdfReader
    except ImportError:
        return "FAILED (pypdf not installed — pip install -e .)", ""
    try:
        reader = PdfReader(io.BytesIO(raw))
        pages = reader.pages[:MAX_PDF_PAGES]
        text = "\n\n".join(p.extract_text() or "" for p in pages)
    except Exception as e:  # noqa: BLE001 — a malformed PDF is a page failure
        return f"FAILED (pdf parse error: {_one_line(str(e), 100)})", ""
    if not text.strip():
        return ocr_pdf(raw)
    total = len(reader.pages)
    note = (
        f" [truncated at {MAX_PDF_PAGES} of {total} pages]"
        if total > MAX_PDF_PAGES
        else ""
    )
    return f"OK{note}", text


def ocr_pdf(raw: bytes) -> tuple[str, str]:
    """Read a scanned PDF by rendering its pages and running OCR.

    A scanned statute is a total loss otherwise, and recognising characters
    is mechanical — no judgement, no model prompt, same bytes in same text
    out. Worth doing. Two things make it a gated fallback rather than the
    default path:

    **The output is a transcription, not the source.** OCR misreads produce
    text that looks exactly like verbatim quotation, and a misread digit in a
    tax rate is a plausible wrong number. The citation-audit agent compares
    the deliverable against this file, so a corrupted digit here would be
    confirmed, not caught — the audit and the error share a cause. The status
    line therefore says OCR, and callers must treat the body as evidence that
    a claim is supported, never as a quotable string.

    **It is slow.** Roughly 4 s per page on CPU, so the page cap is far below
    the text-layer one; a long scanned gazette is deliberately truncated
    rather than allowed to stall a batch for half an hour.

    Requires the optional extra (`pip install -e ".[ocr]"`). Absent, this
    reports the scanned-PDF failure and names the install.
    """
    try:
        import numpy as np
        import pypdfium2 as pdfium
        from rapidocr_onnxruntime import RapidOCR
    except ImportError:
        return (
            "FAILED (no text layer — likely a scanned image PDF; "
            'OCR fallback unavailable, pip install -e ".[ocr]")'
        ), ""
    try:
        doc = pdfium.PdfDocument(raw)
        total = len(doc)
        engine = RapidOCR()
        chunks = []
        for page in list(doc)[:MAX_OCR_PAGES]:
            # scale=2 is ~150 dpi. Below that, recall on body text drops
            # sharply; above it, runtime grows faster than accuracy.
            image = np.array(page.render(scale=2).to_pil())
            result, _ = engine(image)
            chunks.append("\n".join(line[1] for line in (result or [])))
        text = "\n\n".join(chunks)
    except Exception as e:  # noqa: BLE001 — a failed render is a page failure
        return f"FAILED (ocr error: {_one_line(str(e), 100)})", ""
    if not text.strip():
        return "FAILED (no text layer, and OCR found no characters)", ""
    note = (
        f", truncated at {MAX_OCR_PAGES} of {total} pages"
        if total > MAX_OCR_PAGES
        else ""
    )
    return f"OK (OCR — transcription, not verbatim source{note})", text


def ascii_url(url: str) -> str:
    """Rewrite a URL into the all-ASCII form the wire actually carries.

    A URL holding a literal non-ASCII character — `notaires.fr/…/départements`,
    most of INE Portugal — reaches the fetch service intact, and the service's
    HTTP client then dies on it with `'ascii' codec can't encode character`,
    surfacing here as an unexplained 502. Percent-encoding the path and
    IDNA-encoding the host before the request removes the character the
    service cannot handle. Already-encoded sequences pass through untouched,
    so this is a no-op for the ordinary case.
    """
    parts = urllib.parse.urlsplit(url)
    netloc = parts.netloc
    if any(ord(c) > 127 for c in netloc):
        userinfo, at, hostport = netloc.rpartition("@")
        hostname, colon, port = hostport.partition(":")
        try:
            hostname = hostname.encode("idna").decode("ascii")
        except (UnicodeError, ValueError):
            hostname = urllib.parse.quote(hostname, safe="")
        netloc = f"{userinfo}{at}{hostname}{colon}{port}"
    return urllib.parse.urlunsplit(
        (
            parts.scheme,
            netloc,
            urllib.parse.quote(parts.path, safe="/%"),
            urllib.parse.quote(parts.query, safe="=&%+"),
            urllib.parse.quote(parts.fragment, safe="%"),
        )
    )


def url_to_name(url: str) -> str:
    """Stable, filesystem-safe filename for a URL.

    The hash suffix is not decoration: two URLs sharing a long prefix — the
    same gazette with different document ids — would otherwise truncate to
    the same name and one would silently overwrite the other.
    """
    stem = re.sub(r"[^A-Za-z0-9._-]", "-", re.sub(r"^https?://", "", url))[:80]
    digest = hashlib.sha1(url.encode()).hexdigest()[:8]
    return f"{stem}-{digest}.md"


def _service_base() -> str:
    return os.environ.get("CITED_RESEARCH_FETCH_SERVICE", DEFAULT_SERVICE).rstrip("/")


# What each capability needs, and what is lost without it. Checked at
# preflight rather than discovered mid-run: a missing extractor surfaces
# eighty URLs in as a wall of `FAILED`, by which point the run has spent an
# hour and the operator is debugging the wrong thing.
CAPABILITIES = (
    # (import name, install extra, required, what breaks without it)
    ("pypdf", "", True, "PDF sources — legislation, gazettes, statistics"),
    ("pypdfium2", "ocr", False, "OCR fallback for scanned PDFs"),
    ("rapidocr_onnxruntime", "ocr", False, "OCR fallback for scanned PDFs"),
)


def check_dependencies() -> tuple[list[str], bool]:
    """Report each capability's availability. Returns (lines, ok)."""
    import importlib.util

    lines, ok = [], True
    for module, extra, required, loses in CAPABILITIES:
        present = importlib.util.find_spec(module) is not None
        if present:
            lines.append(f"  OK       {module}")
        elif required:
            ok = False
            lines.append(f"  MISSING  {module} — loses {loses}; pip install -e .")
        else:
            lines.append(
                f'  absent   {module} — no {loses}; pip install -e ".[{extra}]"'
            )
    return lines, ok


def check_service() -> int:
    """Probe /healthz. Returns a process exit code."""
    base = _service_base()
    try:
        with urllib.request.urlopen(f"{base}/healthz", timeout=10) as resp:
            if resp.status == 200:
                print(f"fetch service OK: {base}")
                return 0
            print(f"fetch service unhealthy: HTTP {resp.status}", file=sys.stderr)
            return 3
    except urllib.error.HTTPError as e:
        body = _read_error_body(e)
        print(_classify_denial(e.code, body, base), file=sys.stderr)
        return 3
    except (urllib.error.URLError, OSError) as e:
        print(OFFLINE_MESSAGE.format(addr=base), file=sys.stderr)
        print(f"({e})", file=sys.stderr)
        return 3


def _one_line(text: str, limit: int = 120) -> str:
    """Collapse whitespace and truncate, keeping a value header-safe."""
    return " ".join(text.split())[:limit]


def _read_error_body(e: urllib.error.HTTPError) -> str:
    try:
        return e.read().decode("utf-8", errors="replace")
    except Exception:
        return ""


# Markers OpenShell's proxy puts in its own denial body. Anything else at
# 403 came from the service or the upstream site, not the proxy.
_PROXY_DENIAL_MARKERS = ("policy_denied", "not permitted by policy")


def is_proxy_denial(status: int, body: str) -> bool:
    """True only when a 403 came from OpenShell's proxy.

    Three different things answer 403 and they need opposite handling:
    the proxy denying the service address (fatal, operator must act), the
    service declining a URL (`refused:`, recoverable), and the upstream
    site blocking the request (bot protection, very common, recoverable).
    Matching the proxy's own marker rather than treating every unfamiliar
    403 as fatal keeps a routine Cloudflare block from aborting a run.
    """
    if status != 403:
        return False
    lowered = body.lower()
    return any(marker in lowered for marker in _PROXY_DENIAL_MARKERS)


def _classify_denial(status: int, body: str, base: str) -> str:
    if is_proxy_denial(status, body):
        return POLICY_MESSAGE.format(addr=base)
    return f"fetch service returned HTTP {status}: {_one_line(body, 200)}"


def fetch(url: str) -> tuple[str, str, bytes]:
    """Fetch `url` via the service.

    Returns (status_line, content_type, raw_body) where status_line is the
    value for the file's `# Status:` header. The body stays bytes because
    PDFs are a first-class source type here and decoding early would destroy
    them. Raises SystemExit(3) when the service or the policy — rather than
    the upstream page — is the problem.
    """
    base = _service_base()
    encoded = urllib.parse.quote(ascii_url(url), safe="")
    request_url = f"{base}/fetch?url={encoded}"
    try:
        with urllib.request.urlopen(request_url, timeout=TIMEOUT_SECONDS) as resp:
            ctype = resp.headers.get("Content-Type", "")
            return "OK", ctype, resp.read()
    except urllib.error.HTTPError as e:
        body = _read_error_body(e)
        stripped = body.lstrip()
        if is_proxy_denial(e.code, body):
            print(POLICY_MESSAGE.format(addr=base), file=sys.stderr)
            raise SystemExit(3)
        if e.code in (400, 405):
            print(f"Error: bad request to fetch service: {body[:200]}", file=sys.stderr)
            raise SystemExit(1)
        # 403 `refused:`, 502 `upstream error:`, and upstream statuses such
        # as 404 are all page-level failures. Record them and continue —
        # a 20-30% inaccessibility rate is expected, not exceptional.
        #
        # Collapse whitespace before truncating: error bodies are often full
        # HTML error pages, and an embedded newline would split the single-line
        # `# Status:` header and spill markup into the header block.
        return f"FAILED ({e.code}: {_one_line(stripped)})", "", b""
    except (urllib.error.URLError, OSError) as e:
        print(OFFLINE_MESSAGE.format(addr=base), file=sys.stderr)
        print(f"({e})", file=sys.stderr)
        raise SystemExit(3)


def is_pdf(ctype: str, raw: bytes) -> bool:
    """PDF by declared type, or by magic bytes when a host mislabels it.

    `application/octet-stream` on a `.pdf` URL is common enough that going by
    the header alone loses real sources.
    """
    return "pdf" in ctype.lower() or raw[:5] == b"%PDF-"


def render(url: str, status: str, ctype: str, raw: bytes) -> str:
    """Build the fetched-file content, header included."""
    lowered = ctype.lower()
    body = ""
    if status != "OK":
        pass
    elif is_pdf(lowered, raw):
        status, body = pdf_to_text(raw)
    elif lowered and not lowered.startswith(("text/", "application/json")):
        status = f"FAILED (binary content-type {ctype}, not extractable as text)"
    else:
        body = raw.decode("utf-8", errors="replace")
        if "html" in lowered:
            body = html_to_text(body)
            if len(body.strip()) < MIN_HTML_CHARS:
                status = (
                    f"FAILED (empty after extraction, {len(body.strip())} chars — "
                    "likely a JS-rendered page or a challenge interstitial)"
                )
                body = ""
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # `# Status:` must stay one line — agents and the audit step read the
    # header as a fixed three-line block.
    return (
        f"# Fetched: {url}\n"
        f"# Date: {stamp}\n"
        f"# Status: {_one_line(status, 200)}\n\n"
        f"{body}\n"
    )


def fetch_one(slug: str, rel: str, url: str) -> str:
    """Fetch one URL and persist it. Returns the line to print."""
    target = safe_target(slug, rel)
    status, ctype, raw = fetch(url)
    content = render(url, status, ctype, raw)
    atomic_write(target, content)
    # `render` can downgrade OK to FAILED; report what was written, not what
    # the service said.
    status = content.split("# Status: ", 1)[1].split("\n", 1)[0]

    # Encyclopedia articles are mined, not cited. Harvesting their reference
    # lists is deterministic parsing, so it happens here rather than being
    # asked of a model: the sidecar is a plain URL-per-line file the caller
    # feeds straight back into the fetch queue.
    refs_note = ""
    if status.startswith("OK") and "html" in ctype.lower() and is_encyclopedia(url):
        refs = extract_reference_urls(raw.decode("utf-8", errors="replace"), url)
        if refs:
            refs_target = safe_target(slug, rel + ".refs")
            atomic_write(refs_target, "\n".join(refs) + "\n")
            refs_note = f"\t{len(refs)} refs -> {refs_target}"
    return f"{status}\t{target}{refs_note}"


def run_batch(slug: str, lines: list[str]) -> None:
    """Fetch every URL on stdin into `fetched/`, naming files from the URL.

    Exists because the alternative is a hand-rolled shell loop per run, and
    the loop is where filename collisions and swallowed failures get
    reinvented. Failures are counted, not fatal: a 20-30% inaccessibility
    rate is the expected case.
    """
    ok = failed = 0
    for line in lines:
        url = line.strip()
        if not url or url.startswith("#"):
            continue
        # A SystemExit from `fetch` means the service or the policy is down,
        # not that this URL is bad. Let it abort the queue.
        out = fetch_one(slug, f"fetched/{url_to_name(url)}", url)
        if out.startswith("OK"):
            ok += 1
        else:
            failed += 1
        print(out, flush=True)
    print(f"batch complete: ok={ok} failed={failed}", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch a URL via the host-side fetch service and persist it."
    )
    parser.add_argument("--check", action="store_true", help="probe /healthz and exit")
    parser.add_argument(
        "--batch",
        action="store_true",
        help="read URLs from stdin, one per line, into <slug>/fetched/",
    )
    parser.add_argument("slug", nargs="?", help="topic slug")
    parser.add_argument("rel", nargs="?", help="relative path within the slug dir")
    parser.add_argument("url", nargs="?", help="URL to fetch")
    args = parser.parse_args()

    if args.check:
        code = check_service()
        lines, deps_ok = check_dependencies()
        print("\n".join(lines), file=sys.stderr if code else sys.stdout)
        sys.exit(code or (0 if deps_ok else 3))
    if args.batch:
        if not args.slug:
            parser.error("slug is required with --batch")
        require_slug_root(args.slug)
        run_batch(args.slug, sys.stdin.readlines())
        return
    if not (args.slug and args.rel and args.url):
        parser.error("slug, relative-path, and url are required unless --check")

    require_slug_root(args.slug)
    print(fetch_one(args.slug, args.rel, args.url))


if __name__ == "__main__":
    main()
