# Generated By: Claude Code (Claude Opus 4.6)
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Multi-engine search CLI.

Queries multiple search engines and returns a deduplicated JSON list of results.
Designed for use by the cited-research skill coordinator to broaden the URL pool
beyond a single search engine.

Usage (from the skill install directory, via its own venv):
    ~/.claude/skills/cited-research/.venv/bin/python \\
        ~/.claude/skills/cited-research/scripts/multi_search.py \\
        --query "..." --engines ddg --limit 10

For local development from the repo root:
    make test-live
    .venv/bin/python scripts/multi_search.py --query "..." --limit 10

Engines:
    ddg — DuckDuckGo (via the ddgs library, no API key required)

Output:
    JSON array of {url, title, snippet, engine} objects, deduplicated by URL.
"""

import argparse
import json
import sys

SUPPORTED_ENGINES = {"ddg"}


def search_ddg(query: str, limit: int) -> list[dict]:
    """Search DuckDuckGo and return normalized results."""
    try:
        from ddgs import DDGS
    except ImportError:
        print(
            "Error: ddgs not installed. Run: python -m pip install ddgs",
            file=sys.stderr,
        )
        sys.exit(1)

    results = []
    with DDGS() as ddgs:
        for r in ddgs.text(query, max_results=limit):
            results.append(
                {
                    "url": r.get("href", ""),
                    "title": r.get("title", ""),
                    "snippet": r.get("body", ""),
                    "engine": "ddg",
                }
            )
    return results


ENGINE_FUNCTIONS = {
    "ddg": search_ddg,
}


def deduplicate(results: list[dict]) -> list[dict]:
    """Remove duplicate URLs, keeping the first occurrence."""
    seen = set()
    deduped = []
    for r in results:
        url = r["url"]
        if url and url not in seen:
            seen.add(url)
            deduped.append(r)
    return deduped


def main():
    parser = argparse.ArgumentParser(
        description="Multi-engine search for cited-research skill"
    )
    parser.add_argument("--query", required=True, help="Search query string")
    parser.add_argument(
        "--engines",
        default="ddg",
        help="Comma-separated engine list (default: ddg)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Max results per engine (default: 10)",
    )
    args = parser.parse_args()

    engines = [e.strip() for e in args.engines.split(",")]
    unknown = set(engines) - SUPPORTED_ENGINES
    if unknown:
        print(f"Error: unknown engine(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"Supported: {', '.join(sorted(SUPPORTED_ENGINES))}", file=sys.stderr)
        sys.exit(1)

    all_results = []
    for engine in engines:
        try:
            results = ENGINE_FUNCTIONS[engine](args.query, args.limit)
            all_results.extend(results)
        except Exception as e:
            print(f"Warning: {engine} search failed: {e}", file=sys.stderr)

    deduped = deduplicate(all_results)
    json.dump(deduped, sys.stdout, indent=2)
    print()  # trailing newline


if __name__ == "__main__":
    main()
