# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Persist stdin as ~/.local/share/cited-research-data/<slug>/<relative-path>.

Usage:
    python put_data.py <slug> <relative-path-within-slug> < content

The skill's coordinator invokes this instead of the Write tool so that a
single allowlisted Bash rule covers every fetched-content file. Content
is written verbatim from stdin; the wrapper does not transform it.
"""

import sys
import tempfile
from pathlib import Path

from scripts._data_paths import safe_target


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: put_data.py <slug> <relative-path>", file=sys.stderr)
        sys.exit(2)
    slug, rel = sys.argv[1], sys.argv[2]
    target = safe_target(slug, rel)
    target.parent.mkdir(parents=True, exist_ok=True)
    content = sys.stdin.read()

    # Atomic write: stream to a sibling tempfile, then rename into place.
    # Either the whole content lands at `target` or `target` is unchanged —
    # audit agents never read a half-written file. The tempfile is cleaned
    # up on any OSError so no `.part` debris accumulates.
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".part",
            delete=False,
        ) as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)
        tmp_path.replace(target)
    except OSError as e:
        if tmp_path is not None:
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass
        print(f"Error writing {target}: {e}", file=sys.stderr)
        sys.exit(1)
    print(str(target))


if __name__ == "__main__":
    main()
