# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Persist stdin as ./.tmp-cited-research/<slug>/<relative-path>.

Usage:
    python put_data.py <slug> <relative-path-within-slug> < content

The skill's coordinator and the audit sub-agents invoke this instead of
the Write tool so that a single allowlisted Bash rule covers every
fetched-content or audit-report file. Content is written verbatim from
stdin; the wrapper does not transform it.

The slug root (`<DATA_ROOT>/<slug>/`) MUST already exist — this script
refuses to create it. `bootstrap_tmp.sh <slug>` is the only entry point
that provisions the slug root and the parent `.gitignore`. Forcing a
hard error when the slug root is missing keeps the parent `.gitignore`
protection from being silently bypassed (which would risk committing
fetched URLs). Intermediate directories *inside* the slug (e.g.,
`audit/`, `fetched/`) are auto-created by this script.
"""

import sys
import tempfile
from pathlib import Path

from scripts import _data_paths
from scripts._data_paths import safe_target


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: put_data.py <slug> <relative-path>", file=sys.stderr)
        sys.exit(2)
    slug, rel = sys.argv[1], sys.argv[2]
    target = safe_target(slug, rel)
    # Resolve DATA_ROOT via the module rather than a top-level `from … import
    # DATA_ROOT`, so tests monkeypatching `_data_paths.DATA_ROOT` are honored.
    slug_root = _data_paths.DATA_ROOT / slug
    if not slug_root.is_dir():
        print(
            f"Error: slug root does not exist: {slug_root}. "
            f"Run scripts/bootstrap_tmp.sh {slug} first.",
            file=sys.stderr,
        )
        sys.exit(1)
    target.parent.mkdir(parents=True, exist_ok=True)
    content = sys.stdin.read()

    # Atomic write: stream to a sibling tempfile, then rename into place.
    # Either the whole content lands at `target` or `target` is unchanged —
    # audit agents never read a half-written file. The tempfile is cleaned
    # up on any OSError so no `.part` debris accumulates.
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".part",
            delete=False,
        ) as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)
        tmp_path.replace(target)
    except OSError as e:
        if tmp_path is not None:
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass
        print(f"Error writing {target}: {e}", file=sys.stderr)
        sys.exit(1)
    print(str(target))


if __name__ == "__main__":
    main()
