# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Persist stdin as ./.tmp-cited-research/<slug>/<relative-path>.

Usage:
    python put_data.py <slug> <relative-path-within-slug> < content

The skill's coordinator and the audit sub-agents invoke this instead of
the Write tool so that a single allowlisted Bash rule covers every
fetched-content or audit-report file. Content is written verbatim from
stdin; the wrapper does not transform it.

The slug root (`<DATA_ROOT>/<slug>/`) MUST already exist — this script
refuses to create it. `bootstrap_tmp.sh <slug>` is the only entry point
that provisions the slug root and the parent `.gitignore`. Forcing a
hard error when the slug root is missing keeps the parent `.gitignore`
protection from being silently bypassed (which would risk committing
fetched URLs). Intermediate directories *inside* the slug (e.g.,
`audit/`, `fetched/`) are auto-created by this script.
"""

import sys

from scripts._data_paths import atomic_write, require_slug_root, safe_target


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: put_data.py <slug> <relative-path>", file=sys.stderr)
        sys.exit(2)
    slug, rel = sys.argv[1], sys.argv[2]
    target = safe_target(slug, rel)
    require_slug_root(slug)
    atomic_write(target, sys.stdin.read())
    print(str(target))


if __name__ == "__main__":
    main()
