# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Remove ~/.local/share/cited-research-data/<slug>/ recursively.

Usage:
    python reap_data.py <slug>

Idempotent: exits 0 whether the slug directory existed or not. The
coordinator reaps before a fresh run so prior fetched content never
leaks into a new one.
"""

import shutil
import sys

from scripts import _data_paths


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: reap_data.py <slug>", file=sys.stderr)
        sys.exit(2)
    slug = sys.argv[1]
    _data_paths.validate_slug(slug)
    target = _data_paths.DATA_ROOT / slug
    if target.exists():
        shutil.rmtree(target)
    print(str(target))


if __name__ == "__main__":
    main()
