# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Run metadata a report can gather without leaving the machine.

Everything here reads local files. Nothing fetches, and nothing touches a
telemetry endpoint — that separation is deliberate. A sandbox whose network
policy forbids reaching an OTEL collector must not gain a back door to the same
data through the fetch service, so token accounting is done by reading the
session transcript the CLI already wrote to disk.

Three sources, in order of usefulness:

1. **Session transcripts** at `~/.claude/projects/<slug>/*.jsonl`. Assistant
   records carry `message.usage`, which is where input, output and cache token
   counts live. Subagent totals appear separately, as `<subagent_tokens>` in the
   Agent tool's result metadata, because sidechain records are not written to
   the parent transcript.

2. **Environment**, for a reproducibility stamp: skill commit, `ddgs` version,
   the fetch service address.

3. **A rate file**, optional, for currency. Prices are not in any local data
   and change without notice, so they are read from a file the operator owns
   rather than hardcoded — a stale constant in this script would produce a
   confident wrong number, which is worse than no number.

Why a timestamp window rather than a session id: a run that outlives a container
restart continues in a *new* session file. Scoping by id silently truncates the
report at the restart; scoping by window does not. The status line has the same
blind spot.

Usage:
    python -m scripts.run_meta --since 2026-08-16T14:00:00Z
"""

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

# Only these keys are summed. `message.usage` also carries non-numeric entries
# (service_tier, inference_geo) and nested objects (cache_creation), which are
# not token counts and must not be added to a total.
TOKEN_KEYS = (
    "input_tokens",
    "output_tokens",
    "cache_creation_input_tokens",
    "cache_read_input_tokens",
)

SUBAGENT_RE = re.compile(r"<subagent_tokens>(\d+)</subagent_tokens>")


@dataclass
class TokenStats:
    totals: dict = field(default_factory=dict)
    records: int = 0
    subagent_tokens: int = 0
    subagent_count: int = 0
    sessions: set = field(default_factory=set)
    first: str = ""
    last: str = ""
    models: dict = field(default_factory=dict)
    scanned_files: int = 0

    @property
    def billable(self) -> int:
        """Tokens excluding cache reads.

        Cache reads dominate the raw total by an order of magnitude and are
        priced differently everywhere, so a single summed number is misleading.
        This is the figure to reason about; the raw components stay visible.
        """
        return sum(
            self.totals.get(k, 0)
            for k in ("input_tokens", "output_tokens", "cache_creation_input_tokens")
        )


def project_dir(cwd: Path | None = None) -> Path:
    """Locate the CLI's transcript directory for a working directory.

    The CLI encodes the project path by replacing separators with hyphens, and
    keys the directory on the path the *session* started in. A report run from a
    subdirectory — which is the normal case, since the deliverable lives under
    `research/<slug>/` — would miss it on an exact match, so walk upward and take
    the first encoded ancestor that exists. Returns the exact-match path when
    nothing matches, so the caller reports a clean absence rather than guessing.
    """
    cwd = (cwd or Path.cwd()).resolve()
    root = Path.home() / ".claude" / "projects"
    exact = root / str(cwd).replace("/", "-")
    for candidate in [cwd, *cwd.parents]:
        path = root / str(candidate).replace("/", "-")
        if path.is_dir():
            return path
    return exact


def _in_window(stamp: str, since: str, until: str) -> bool:
    if not stamp:
        return not since  # undated records only count when no window is set
    if since and stamp < since:
        return False
    if until and stamp > until:
        return False
    return True


def read_tokens(
    proj: Path, since: str = "", until: str = "", cwd_filter: str = ""
) -> TokenStats:
    """Sum token usage from every transcript in `proj` inside the window."""
    stats = TokenStats()
    if not proj.is_dir():
        return stats
    for path in sorted(proj.glob("*.jsonl")):
        stats.scanned_files += 1
        for line in path.read_text(errors="replace").splitlines():
            if not line.strip():
                continue
            # Cheap prefilter: most lines carry neither usage nor an agent
            # result, and json.loads on a 5 MB transcript is the slow part.
            has_usage = '"usage"' in line
            sub = SUBAGENT_RE.search(line)
            if not has_usage and not sub:
                continue
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            stamp = rec.get("timestamp") or ""
            if not _in_window(stamp, since, until):
                continue
            if cwd_filter and rec.get("cwd") and cwd_filter not in rec["cwd"]:
                continue
            if sub:
                stats.subagent_tokens += int(sub.group(1))
                stats.subagent_count += 1
            msg = rec.get("message")
            usage = msg.get("usage") if isinstance(msg, dict) else None
            if isinstance(usage, dict):
                stats.records += 1
                if rec.get("sessionId"):
                    stats.sessions.add(rec["sessionId"])
                model = (msg or {}).get("model")
                if model:
                    stats.models[model] = stats.models.get(model, 0) + 1
                for key in TOKEN_KEYS:
                    val = usage.get(key)
                    if isinstance(val, int):
                        stats.totals[key] = stats.totals.get(key, 0) + val
            if stamp:
                stats.first = min(stats.first or stamp, stamp)
                stats.last = max(stats.last, stamp)
    return stats


def load_rates(path: Path | None) -> dict:
    """Load a USD-per-million-tokens rate table, if the operator supplied one.

    Deliberately not defaulted. No rate file means the report prints tokens and
    says money is unpriced, which is the honest outcome — inventing a price is
    the failure mode this guards against.
    """
    if path is None:
        env = os.environ.get("CITED_RESEARCH_RATES")
        path = Path(env) if env else None
    if path is None or not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (ValueError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def price(stats: TokenStats, rates: dict) -> tuple[float, list[str]]:
    """Return (usd, notes). Rates are USD per million tokens, by usage key."""
    notes = []
    usd = 0.0
    per_million = rates.get("usd_per_million_tokens") or {}
    if not per_million:
        return 0.0, ["no rate file — token counts only"]
    for key, count in sorted(stats.totals.items()):
        rate = per_million.get(key)
        if rate is None:
            notes.append(f"{key}: unpriced")
            continue
        usd += count / 1_000_000 * float(rate)
    sub_rate = per_million.get("subagent_tokens")
    if sub_rate is not None and stats.subagent_tokens:
        usd += stats.subagent_tokens / 1_000_000 * float(sub_rate)
    elif stats.subagent_tokens:
        notes.append("subagent_tokens: unpriced")
    if rates.get("as_of"):
        notes.append(f"rates as of {rates['as_of']}")
    return usd, notes


def environment(skill_root: Path | None = None) -> dict:
    """Reproducibility stamp: what code and services produced this run."""
    skill_root = skill_root or Path(__file__).resolve().parent.parent
    env = {
        "python": sys.version.split()[0],
        "skill_path": str(skill_root),
        "fetch_service": os.environ.get(
            "CITED_RESEARCH_FETCH_SERVICE", "http://172.30.0.21:8090"
        ),
    }
    try:
        import ddgs  # noqa: F401
        from importlib.metadata import version

        env["ddgs"] = version("ddgs")
    except Exception:  # noqa: BLE001 — absence is itself reportable
        env["ddgs"] = "not installed"
    try:
        out = subprocess.run(
            ["git", "-C", str(skill_root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        env["skill_commit"] = out.stdout.strip() or "unknown"
    except Exception:  # noqa: BLE001
        env["skill_commit"] = "unknown"
    return env


def duration_hours(first: str, last: str) -> float:
    """Wall-clock hours between two ISO timestamps, 0.0 if unparseable."""
    try:
        a = datetime.fromisoformat(first.replace("Z", "+00:00"))
        b = datetime.fromisoformat(last.replace("Z", "+00:00"))
    except ValueError:
        return 0.0
    return max(0.0, (b - a).total_seconds() / 3600)


def _fmt(n: int) -> str:
    return f"{n:,}"


def render(stats: TokenStats, rates: dict, env: dict) -> list[str]:
    """Render the COST and ENVIRONMENT sections as report lines."""
    out = ["COST AND EFFORT"]
    if not stats.records:
        out.append("  no session transcript found — token accounting unavailable")
    else:
        out.append(
            f"  {_fmt(stats.billable)} billable tokens "
            f"(input + output + cache creation), excluding cache reads"
        )
        for key in TOKEN_KEYS:
            if key in stats.totals:
                out.append(f"    {key:34} {_fmt(stats.totals[key]):>15}")
        if stats.subagent_count:
            out.append(
                f"    {'subagent_tokens':34} {_fmt(stats.subagent_tokens):>15}"
                f"  across {stats.subagent_count} agent results"
            )
        usd, notes = price(stats, rates)
        if usd:
            out.append(f"  estimated USD {usd:,.2f}")
        for note in notes:
            out.append(f"  ! {note}")
        hours = duration_hours(stats.first, stats.last)
        if hours:
            out.append(f"  wall clock {hours:.1f}h  ({stats.first} to {stats.last})")
        if len(stats.sessions) > 1:
            out.append(
                f"  ! spans {len(stats.sessions)} sessions — a status line scoped to "
                "one session would undercount this run"
            )
        if stats.models:
            out.append(
                "  models: "
                + ", ".join(f"{m} ({n})" for m, n in sorted(stats.models.items()))
            )
    out.append("")
    out.append("ENVIRONMENT")
    for key in ("skill_commit", "ddgs", "python", "fetch_service"):
        out.append(f"  {key:16} {env.get(key, 'unknown')}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", default="", help="ISO timestamp lower bound")
    parser.add_argument("--until", default="", help="ISO timestamp upper bound")
    parser.add_argument("--rates", default=None, help="path to a JSON rate file")
    args = parser.parse_args()

    stats = read_tokens(project_dir(), args.since, args.until)
    rates = load_rates(Path(args.rates) if args.rates else None)
    print("\n".join(render(stats, rates, environment())))


if __name__ == "__main__":
    main()
