# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Run metadata a report can gather without leaving the machine.

Everything here reads local files. Nothing fetches, and nothing touches a
telemetry endpoint — that separation is deliberate. A sandbox whose network
policy forbids reaching an OTEL collector must not gain a back door to the same
data through the fetch service, so token accounting is done by reading the
session transcript the CLI already wrote to disk.

Three sources, in order of usefulness:

1. **Session transcripts** at `~/.claude/projects/<slug>/*.jsonl`. Assistant
   records carry `message.usage`, which is where input, output and cache token
   counts live. Subagent totals appear separately in the Agent tool's result
   metadata, because sidechain records are not written to the parent transcript.
   Two renderings exist in the wild — see `SUBAGENT_RE`.

   **Scope these by window.** A project directory accumulates every session that
   ever ran there, and `/clear` does not start a new one, so an unscoped read
   reports unrelated sessions as part of this run. `run_start()` derives the
   lower bound from the run's own artifacts; `run_report.py` applies it by
   default.

2. **Environment**, for a reproducibility stamp: skill commit, `ddgs` version,
   the fetch service address.

3. **A rate file**, optional, for currency. Prices are not in any local data
   and change without notice, so they are read from a file the operator owns
   rather than hardcoded — a stale constant in this script would produce a
   confident wrong number, which is worse than no number.

Why a timestamp window rather than a session id: a run that outlives a container
restart continues in a *new* session file. Scoping by id silently truncates the
report at the restart; scoping by window does not. The status line has the same
blind spot.

Usage:
    python -m scripts.run_meta --since 2026-08-16T14:00:00Z
"""

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Only these keys are summed. `message.usage` also carries non-numeric entries
# (service_tier, inference_geo) and nested objects (cache_creation), which are
# not token counts and must not be added to a total.
TOKEN_KEYS = (
    "input_tokens",
    "output_tokens",
    "cache_creation_input_tokens",
    "cache_read_input_tokens",
)

# Two renderings, because the CLI changed format mid-2026 and transcripts from
# either era can sit in the same project directory. Matching only the older tag
# form silently reported zero subagent tokens for every newer run.
#   old: <subagent_tokens>26701</subagent_tokens>
#   new: subagent_tokens: 207684\ntool_uses: 18   (inside a <usage> block)
# The colon form is deliberately not anchored to what follows it — anchoring on
# `tool_uses` was measured to miss results that omit it.
SUBAGENT_RE = re.compile(
    r"<subagent_tokens>(\d+)</subagent_tokens>|subagent_tokens:\s*(\d+)"
)

# Tolerates whitespace after the colon. The CLI writes compact JSON, but a
# transcript that has been through any re-serialisation has a space there, and
# silently matching nothing would zero out active time rather than erroring.
TIMESTAMP_RE = re.compile(r'"timestamp":\s*"([^"]+)"')

# A gap longer than this is someone not looking at the session, not work in
# progress. Measured against a real run: the longest gap that was genuinely work
# was 14.7 minutes (a slow subagent), and the next gap up was 48.5 hours — an
# overnight break between sittings. Every threshold from 15 to 60 minutes gives
# the same answer for that run, so this sits mid-band rather than on an edge.
# Runs whose agents legitimately exceed it will say so: the report prints how
# many gaps were excluded and how long the largest was.
IDLE_GAP_SECONDS = 1800


@dataclass
class TokenStats:
    totals: dict = field(default_factory=dict)
    records: int = 0
    subagent_tokens: int = 0
    subagent_count: int = 0
    sessions: set = field(default_factory=set)
    first: str = ""
    last: str = ""
    models: dict = field(default_factory=dict)
    scanned_files: int = 0
    stamps: list = field(default_factory=list)

    @property
    def billable(self) -> int:
        """Tokens excluding cache reads.

        Cache reads dominate the raw total by an order of magnitude and are
        priced differently everywhere, so a single summed number is misleading.
        This is the figure to reason about; the raw components stay visible.
        """
        return sum(
            self.totals.get(k, 0)
            for k in ("input_tokens", "output_tokens", "cache_creation_input_tokens")
        )


def project_dir(cwd: Path | None = None) -> Path:
    """Locate the CLI's transcript directory for a working directory.

    The CLI encodes the project path by replacing separators with hyphens, and
    keys the directory on the path the *session* started in. A report run from a
    subdirectory — which is the normal case, since the deliverable lives under
    `research/<slug>/` — would miss it on an exact match, so walk upward and take
    the first encoded ancestor that exists. Returns the exact-match path when
    nothing matches, so the caller reports a clean absence rather than guessing.
    """
    cwd = (cwd or Path.cwd()).resolve()
    root = Path.home() / ".claude" / "projects"
    exact = root / str(cwd).replace("/", "-")
    for candidate in [cwd, *cwd.parents]:
        path = root / str(candidate).replace("/", "-")
        if path.is_dir():
            return path
    return exact


def run_start(slug_root: Path) -> tuple[str, str]:
    """Infer when this run began, from the run's own artifacts on disk.

    Returns `(iso_timestamp, signal_name)`, or `("", "")` when nothing usable
    exists. The caller reports the signal name so a reader can see the bound was
    inferred rather than recorded.

    Why this exists: token accounting globs every transcript in the project
    directory, and `/clear` starts a new conversation without starting a new
    project directory. Unscoped, a run reported the span of every unrelated
    session sharing that directory — measured once at 173.8h and 23.9M tokens
    for a run that was actually 1.7h and 1.6M.

    Preferred signal is the `started` file `bootstrap_tmp.sh` writes at the top
    of Phase 1, which is recorded rather than inferred. The artifact-based
    fallbacks exist for runs bootstrapped before that file was added; they land
    minutes late, which is enough to drop the first agents dispatched — measured
    at 16:06:21Z inferred against a true 16:03:16Z, losing four agent results.

    The slug directory's own birth time would be exact too, but CPython on Linux
    does not expose `st_birthtime`.

    Deliberately not used: `agents.tsv` mtime, which tracks the *last* append
    rather than the first, and so trails the run by its whole duration.
    """
    marker = slug_root / "started"
    if marker.is_file():
        stamp = marker.read_text(errors="replace").strip()
        if stamp:
            return stamp, "bootstrap_tmp.sh 'started' marker"

    cands: list[tuple[str, str]] = []

    search = slug_root / "search"
    if search.is_dir():
        stamps = [f.stat().st_mtime for f in search.iterdir() if f.is_file()]
        if stamps:
            cands.append((_iso(min(stamps)), "earliest search/*.json mtime"))

    # Content-based, so it survives copy, rsync and filesystems that drop mtime.
    fetched = slug_root / "fetched"
    if fetched.is_dir():
        earliest = ""
        for path in fetched.glob("*.md"):
            try:
                head = path.read_text(errors="replace").splitlines()[:5]
            except OSError:
                continue
            for line in head:
                if line.startswith("# Date:"):
                    stamp = line.split(":", 1)[1].strip()
                    if stamp and (not earliest or stamp < earliest):
                        earliest = stamp
                    break
        if earliest:
            cands.append((earliest, "earliest fetched '# Date:' header"))

    if not cands:
        return "", ""
    return min(cands)


def _iso(epoch: float) -> str:
    """Epoch seconds to the UTC ISO form the transcript timestamps use."""
    return (
        datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[
            :-3
        ]
        + "Z"
    )


def _in_window(stamp: str, since: str, until: str) -> bool:
    if not stamp:
        return not since  # undated records only count when no window is set
    if since and stamp < since:
        return False
    if until and stamp > until:
        return False
    return True


def read_tokens(
    proj: Path, since: str = "", until: str = "", cwd_filter: str = ""
) -> TokenStats:
    """Sum token usage from every transcript in `proj` inside the window."""
    stats = TokenStats()
    if not proj.is_dir():
        return stats
    for path in sorted(proj.glob("*.jsonl")):
        stats.scanned_files += 1
        for line in path.read_text(errors="replace").splitlines():
            if not line.strip():
                continue
            # Timestamps come off the raw line by regex, before the prefilter
            # below drops most lines. Active time wants every record, not just
            # the ones carrying tokens — more points means tighter gaps — and a
            # regex avoids the json.loads that the prefilter exists to skip.
            ts = TIMESTAMP_RE.search(line)
            if ts and _in_window(ts.group(1), since, until):
                stats.stamps.append(ts.group(1))
            # Cheap prefilter: most lines carry neither usage nor an agent
            # result, and json.loads on a 5 MB transcript is the slow part.
            has_usage = '"usage"' in line
            sub = SUBAGENT_RE.search(line)
            if not has_usage and not sub:
                continue
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            stamp = rec.get("timestamp") or ""
            if not _in_window(stamp, since, until):
                continue
            if cwd_filter and rec.get("cwd") and cwd_filter not in rec["cwd"]:
                continue
            # Only tool results carry real subagent usage. Assistant records can
            # contain the same literal as prose, because SKILL.md requires the
            # run report — which prints `subagent_tokens: N` — to be pasted into
            # the reply. Counting those would inflate every subsequent run.
            if sub and rec.get("type") != "assistant":
                stats.subagent_tokens += int(sub.group(1) or sub.group(2))
                stats.subagent_count += 1
            msg = rec.get("message")
            usage = msg.get("usage") if isinstance(msg, dict) else None
            if isinstance(usage, dict):
                stats.records += 1
                if rec.get("sessionId"):
                    stats.sessions.add(rec["sessionId"])
                model = (msg or {}).get("model")
                if model:
                    stats.models[model] = stats.models.get(model, 0) + 1
                for key in TOKEN_KEYS:
                    val = usage.get(key)
                    if isinstance(val, int):
                        stats.totals[key] = stats.totals.get(key, 0) + val
            if stamp:
                stats.first = min(stats.first or stamp, stamp)
                stats.last = max(stats.last, stamp)
    return stats


def load_rates(path: Path | None) -> dict:
    """Load a USD-per-million-tokens rate table, if the operator supplied one.

    Deliberately not defaulted. No rate file means the report prints tokens and
    says money is unpriced, which is the honest outcome — inventing a price is
    the failure mode this guards against.
    """
    if path is None:
        env = os.environ.get("CITED_RESEARCH_RATES")
        path = Path(env) if env else None
    if path is None or not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (ValueError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def price(stats: TokenStats, rates: dict) -> tuple[float, list[str]]:
    """Return (usd, notes). Rates are USD per million tokens, by usage key."""
    notes = []
    usd = 0.0
    per_million = rates.get("usd_per_million_tokens") or {}
    if not per_million:
        return 0.0, ["no rate file — token counts only"]
    for key, count in sorted(stats.totals.items()):
        rate = per_million.get(key)
        if rate is None:
            notes.append(f"{key}: unpriced")
            continue
        usd += count / 1_000_000 * float(rate)
    sub_rate = per_million.get("subagent_tokens")
    if sub_rate is not None and stats.subagent_tokens:
        usd += stats.subagent_tokens / 1_000_000 * float(sub_rate)
    elif stats.subagent_tokens:
        notes.append("subagent_tokens: unpriced")
    if rates.get("as_of"):
        notes.append(f"rates as of {rates['as_of']}")
    return usd, notes


def environment(skill_root: Path | None = None) -> dict:
    """Reproducibility stamp: what code and services produced this run."""
    skill_root = skill_root or Path(__file__).resolve().parent.parent
    env = {
        "python": sys.version.split()[0],
        "skill_path": str(skill_root),
        "fetch_service": os.environ.get(
            "CITED_RESEARCH_FETCH_SERVICE", "http://172.30.0.21:8090"
        ),
    }
    try:
        import ddgs  # noqa: F401
        from importlib.metadata import version

        env["ddgs"] = version("ddgs")
    except Exception:  # noqa: BLE001 — absence is itself reportable
        env["ddgs"] = "not installed"
    try:
        out = subprocess.run(
            ["git", "-C", str(skill_root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        env["skill_commit"] = out.stdout.strip() or "unknown"
    except Exception:  # noqa: BLE001
        env["skill_commit"] = "unknown"
    return env


def active_time(stamps: list, idle_gap: int = IDLE_GAP_SECONDS) -> tuple:
    """Hours of work, excluding stretches where nobody was driving the session.

    Returns `(hours, excluded_count, largest_excluded_seconds)`.

    Wall clock answers "when did this happen", not "how long did it take". An
    unattended session inflates it without bound — a run measured at 2.6h of
    work reported a 50.4h span purely because it resumed two days later. Summing
    only the gaps below `idle_gap` gives the figure people actually mean.

    The two diagnostics exist so the threshold is auditable rather than trusted:
    if a run excludes many gaps, or one only slightly over the limit, the
    threshold is wrong for that run and the reader can see it.
    """
    parsed = sorted(p for p in (_parse(s) for s in stamps) if p is not None)
    if len(parsed) < 2:
        return 0.0, 0, 0.0
    active = 0.0
    excluded = 0
    largest = 0.0
    for a, b in zip(parsed, parsed[1:]):
        gap = (b - a).total_seconds()
        if gap <= 0:
            continue
        if gap <= idle_gap:
            active += gap
        else:
            excluded += 1
            largest = max(largest, gap)
    return active / 3600, excluded, largest


def _parse(stamp: str):
    """ISO timestamp to datetime, or None when unparseable."""
    try:
        return datetime.fromisoformat(stamp.replace("Z", "+00:00"))
    except ValueError:
        return None


def duration_hours(first: str, last: str) -> float:
    """Wall-clock hours between two ISO timestamps, 0.0 if unparseable."""
    try:
        a = datetime.fromisoformat(first.replace("Z", "+00:00"))
        b = datetime.fromisoformat(last.replace("Z", "+00:00"))
    except ValueError:
        return 0.0
    return max(0.0, (b - a).total_seconds() / 3600)


def _fmt(n: int) -> str:
    return f"{n:,}"


def render(stats: TokenStats, rates: dict, env: dict) -> list[str]:
    """Render the COST and ENVIRONMENT sections as report lines."""
    out = ["COST AND EFFORT"]
    if not stats.records:
        out.append("  no session transcript found — token accounting unavailable")
    else:
        out.append(
            f"  {_fmt(stats.billable)} billable tokens "
            f"(input + output + cache creation), excluding cache reads"
        )
        for key in TOKEN_KEYS:
            if key in stats.totals:
                out.append(f"    {key:34} {_fmt(stats.totals[key]):>15}")
        if stats.subagent_count:
            out.append(
                f"    {'subagent_tokens':34} {_fmt(stats.subagent_tokens):>15}"
                f"  across {stats.subagent_count} agent results"
            )
        usd, notes = price(stats, rates)
        if usd:
            out.append(f"  estimated USD {usd:,.2f}")
        for note in notes:
            out.append(f"  ! {note}")
        hours = duration_hours(stats.first, stats.last)
        active, idle_gaps, largest = active_time(stats.stamps)
        if active:
            line = f"  active {active:.1f}h"
            if idle_gaps:
                line += (
                    f"  ({idle_gaps} idle gap{'s' if idle_gaps > 1 else ''} over "
                    f"{IDLE_GAP_SECONDS // 60}m excluded, largest "
                    f"{largest / 3600:.1f}h)"
                )
            else:
                line += (
                    f"  (no gap over {IDLE_GAP_SECONDS // 60}m — "
                    "worked straight through)"
                )
            out.append(line)
        if hours:
            out.append(f"  span {hours:.1f}h  ({stats.first} to {stats.last})")
            if active and hours > active * 1.5:
                out.append(
                    "  ! span is elapsed time, not effort — this run sat idle "
                    "between sittings"
                )
        if len(stats.sessions) > 1:
            out.append(
                f"  ! spans {len(stats.sessions)} sessions — a status line scoped to "
                "one session would undercount this run"
            )
        if stats.models:
            out.append(
                "  models: "
                + ", ".join(f"{m} ({n})" for m, n in sorted(stats.models.items()))
            )
    out.append("")
    out.append("ENVIRONMENT")
    for key in ("skill_commit", "ddgs", "python", "fetch_service"):
        out.append(f"  {key:16} {env.get(key, 'unknown')}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", default="", help="ISO timestamp lower bound")
    parser.add_argument("--until", default="", help="ISO timestamp upper bound")
    parser.add_argument("--rates", default=None, help="path to a JSON rate file")
    args = parser.parse_args()

    stats = read_tokens(project_dir(), args.since, args.until)
    rates = load_rates(Path(args.rates) if args.rates else None)
    print("\n".join(render(stats, rates, environment())))


if __name__ == "__main__":
    main()
