# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Post-run validation report for a cited-research topic.

Reads the artifacts a run leaves on disk and prints a fixed report. Nothing
here is a judgement call, so nothing is left to the model: the numbers are
counted from files, and the same run always produces the same report.

What it reads:
    .tmp-cited-research/<slug>/agents.tsv    one line per dispatched agent
    .tmp-cited-research/<slug>/search/*.json multi_search output
    .tmp-cited-research/<slug>/fetched/*.md  fetched pages (header status)
    research/<slug>/citations.md             tiers and access failures
    research/<slug>/audit/citation-audit.md  per-citation grades

Usage:
    python run_report.py <slug> [--deliverable-dir DIR]
"""

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from scripts import _data_paths

# Severity order, best to worst. Grades print in this order, never by count.
GRADES = ("VERIFIED", "PARTIAL", "INACCURATE", "INACCESSIBLE", "NOT FOUND")

# The tier scale is ordinal and fixed, so all four always print — including
# a zero. "Tier 1: 0" is a finding (no primary sources), and sorting tiers
# by frequency would hide it in the middle of the list.
TIERS = ("Tier 1", "Tier 2", "Tier 3", "Tier 4")

# Plain-English gloss for the HTTP statuses a fetch can fail with, so the
# report does not make the reader look them up.
HTTP_MEANING = {
    "400": "bad request",
    "401": "auth required",
    "403": "blocked (bot protection or forbidden)",
    "404": "not found",
    "410": "gone",
    "429": "rate limited",
    "500": "server error",
    "502": "upstream error (service could not reach the site)",
    "503": "service unavailable",
    "504": "upstream timeout",
    "other": "no status code recorded",
}


@dataclass
class SearchStats:
    queries: int = 0
    results: int = 0
    single_wave: int = 0
    unparsable: int = 0
    engines: Counter = field(default_factory=Counter)
    unique_by_wave: Counter = field(default_factory=Counter)


@dataclass
class FetchStats:
    total: int = 0
    ok: int = 0
    failed: int = 0
    refs: int = 0
    reasons: Counter = field(default_factory=Counter)


@dataclass
class CiteStats:
    defined: int = 0
    cited: int = 0
    access_failed: int = 0
    tiers: Counter = field(default_factory=Counter)


def _rows(
    label: str,
    counter: Counter,
    total: int | None = None,
    order: tuple[str, ...] | None = None,
    show_zero: bool = False,
    gloss: dict[str, str] | None = None,
) -> list[str]:
    """Render a counter as aligned rows.

    `order` fixes the row order for ordinal scales (tiers, grades), where
    sorting by frequency would be misleading. Without it, rows are sorted by
    count descending, which is what you want for engines and error codes.
    """
    if not counter and not show_zero:
        return [f"  {label}: none recorded"]
    if order:
        keys = [k for k in order if show_zero or counter.get(k)]
    else:
        keys = [
            k for k, _ in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0])))
        ]
    out = []
    for key in keys:
        n = counter.get(key, 0)
        pct = f"  ({n / total:.0%})" if total else ""
        note = f"  {gloss[key]}" if gloss and key in gloss else ""
        out.append(f"    {str(key):<12} {n:>4}{pct}{note}")
    return out


def read_agents(slug_root: Path) -> tuple[Counter, list[str]]:
    """Tally agent outcomes from agents.tsv (`name<TAB>mode<TAB>status`)."""
    path = slug_root / "agents.tsv"
    outcomes: Counter = Counter()
    dropped: list[str] = []
    if not path.is_file():
        return outcomes, dropped
    for line in path.read_text().splitlines():
        parts = [p.strip() for p in line.split("\t")]
        if len(parts) < 3 or not parts[0] or parts[0].startswith("#"):
            continue
        name, mode, status = parts[0], parts[1], parts[2].lower()
        outcomes[status] += 1
        if status != "ok":
            dropped.append(f"{name} ({mode}): {status}")
    return outcomes, dropped


def read_search(slug_root: Path) -> "SearchStats":
    """Aggregate multi_search coverage across every query file."""
    search_dir = slug_root / "search"
    stats = SearchStats()
    if not search_dir.is_dir():
        return stats
    for f in sorted(search_dir.glob("*.json")):
        try:
            payload = json.loads(f.read_text())
        except (ValueError, OSError):
            stats.unparsable += 1
            continue
        if not isinstance(payload, dict):
            stats.unparsable += 1
            continue
        stats.queries += 1
        results = payload.get("results") or []
        stats.results += len(results)
        cov = payload.get("coverage") or {}
        if cov.get("single_wave"):
            stats.single_wave += 1
        for key in ("wave_a_backends", "wave_b_backends"):
            for engine in (cov.get(key) or "").split(","):
                if engine.strip():
                    stats.engines[engine.strip()] += 1
        for wave, n in (cov.get("unique_by_wave") or {}).items():
            stats.unique_by_wave[wave] += n
    return stats


def read_fetched(slug_root: Path) -> "FetchStats":
    """Count fetch outcomes and harvested encyclopedia references."""
    fetched = slug_root / "fetched"
    stats = FetchStats()
    if not fetched.is_dir():
        return stats
    for f in sorted(fetched.glob("*.md")):
        head = f.read_text(errors="replace").split("\n\n", 1)[0]
        m = re.search(r"^# Status: (OK|FAILED)(.*)$", head, re.MULTILINE)
        if not m:
            continue
        stats.total += 1
        if m.group(1) == "OK":
            stats.ok += 1
        else:
            stats.failed += 1
            code = re.search(r"\((\d{3})", m.group(2))
            stats.reasons[code.group(1) if code else "other"] += 1
    for f in fetched.glob("*.refs"):
        stats.refs += len([ln for ln in f.read_text().splitlines() if ln.strip()])
    return stats


def read_citations(deliverable: Path) -> "CiteStats":
    """Tier histogram and access failures from citations.md."""
    path = deliverable / "citations.md"
    stats = CiteStats()
    if not path.is_file():
        return stats
    text = path.read_text()
    stats.defined = len(re.findall(r"^\*\*\[\d+\]\*\*", text, re.MULTILINE))
    for tier in re.findall(r"^\*\*Tier:\*\*\s*(\d)", text, re.MULTILINE):
        stats.tiers[f"Tier {tier}"] += 1
    stats.access_failed = len(re.findall(r"\*\*Access:\*\*\s*FAILED", text))

    cited: set[str] = set()
    for md in deliverable.rglob("*.md"):
        if md.name == "citations.md" or "audit" in md.parts:
            continue
        cited |= set(re.findall(r"\[(\d+)\]", md.read_text()))
    stats.cited = len(cited)
    return stats


def read_audit(deliverable: Path) -> Counter:
    """Tally per-citation grades from the citation audit report.

    Prefers the machine-readable ledger the audit agent is required to emit
    (`[N] GRADE`, one per line). Falls back to `**Grade:**` lines in prose,
    which undercounts when an auditor summarises verified citations in a
    list instead of giving each its own section — observed on a real run
    where 33 VERIFIED citations produced 0 parseable grades.
    """
    path = deliverable / "audit" / "citation-audit.md"
    grades: Counter = Counter()
    if not path.is_file():
        return grades
    text = path.read_text()

    ledger = re.search(
        r"^##+\s*Grade Ledger\s*$(.*?)(?=^##\s|\Z)", text, re.MULTILINE | re.DOTALL
    )
    if ledger:
        for _num, grade in re.findall(
            r"^\s*[-*]?\s*\[(\d+)\]\s+([A-Z ]+?)\s*$", ledger.group(1), re.MULTILINE
        ):
            if grade.strip() in GRADES:
                grades[grade.strip()] += 1
        if grades:
            return grades

    for line in text.splitlines():
        m = re.search(r"\*\*Grade:\s*([A-Z ]+?)\s*(?:—|--|\*\*)", line)
        if m and m.group(1).strip() in GRADES:
            grades[m.group(1).strip()] += 1
    return grades


def build_report(slug: str, slug_root: Path, deliverable: Path) -> str:
    outcomes, dropped = read_agents(slug_root)
    search = read_search(slug_root)
    fetched = read_fetched(slug_root)
    cites = read_citations(deliverable)
    grades = read_audit(deliverable)

    lines = [f"cited-research run report — {slug}", "=" * 60, "", "AGENTS"]
    dispatched = sum(outcomes.values())
    if not dispatched:
        lines.append("  no agents.tsv — agent outcomes not recorded for this run")
    else:
        lost = dispatched - outcomes.get("ok", 0)
        lines.append(
            f"  dispatched {dispatched}, completed {outcomes.get('ok', 0)}, "
            f"lost {lost} ({lost / dispatched:.0%} signal loss)"
        )
        lines += _rows("outcomes", outcomes, dispatched)
        for d in dropped:
            lines.append(f"    ! {d}")

    lines += ["", "SEARCH"]
    if not search.queries:
        lines.append("  no search/*.json — queries not persisted for this run")
    else:
        lines.append(
            f"  {search.queries} queries, {search.results} results, "
            f"{len(search.engines)} engines used"
        )
        if search.single_wave:
            lines.append(
                f"  ! {search.single_wave}/{search.queries} queries returned "
                "a single wave (not two independent samples)"
            )
        if search.unparsable:
            lines.append(f"  ! {search.unparsable} unparsable result files")
        lines += _rows("engines", search.engines)
        if search.unique_by_wave:
            lines += _rows("unique URLs by wave", search.unique_by_wave)

    lines += ["", "FETCH"]
    if not fetched.total:
        lines.append("  no fetched pages found")
    else:
        rate = fetched.failed / fetched.total
        lines.append(
            f"  {fetched.total} attempted, {fetched.ok} usable, "
            f"{fetched.failed} failed ({rate:.1%})"
        )
        if fetched.reasons:
            lines.append("  failures by HTTP status:")
        lines += _rows("failure codes", fetched.reasons, gloss=HTTP_MEANING)
        if fetched.refs:
            lines.append(f"    encyclopedia refs harvested {fetched.refs:>4}")

    lines += ["", "CITATIONS"]
    if not cites.defined:
        lines.append("  no citations.md found")
    else:
        lines.append(
            f"  {cites.defined} defined, {cites.cited} referenced in prose, "
            f"{cites.access_failed} marked access-failed"
        )
        lines += _rows("tiers", cites.tiers, cites.defined, order=TIERS, show_zero=True)
        orphans = cites.defined - cites.cited
        if orphans > 0:
            lines.append(f"    ! {orphans} defined but never cited")

    lines += ["", "VERIFICATION"]
    total_graded = sum(grades.values())
    if not total_graded:
        lines.append("  no graded citations found in audit/citation-audit.md")
    else:
        verified = grades.get("VERIFIED", 0)
        lines.append(
            f"  {total_graded} citations audited, {verified} verified "
            f"({verified / total_graded:.0%}), "
            f"{total_graded - verified} not"
        )
        lines += _rows("grades", grades, total_graded, order=GRADES)
        unchecked = cites.defined - total_graded
        if unchecked > 0:
            lines.append(f"    ! {unchecked} citations never audited")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Post-run report for a research topic")
    parser.add_argument("slug", help="topic slug")
    parser.add_argument(
        "--deliverable-dir",
        default=None,
        help="deliverable directory (default: research/<slug>)",
    )
    args = parser.parse_args()

    slug_root = _data_paths.DATA_ROOT / args.slug
    deliverable = (
        Path(args.deliverable_dir)
        if args.deliverable_dir
        else Path.cwd() / "research" / args.slug
    )
    print(build_report(args.slug, slug_root, deliverable))
    if not slug_root.is_dir() and not deliverable.is_dir():
        print(
            f"\nError: neither {slug_root} nor {deliverable} exists.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
