# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Dump one candidate's raw response so its markup can be inspected.

`probe_search_alternatives.py` reports whether a candidate answers at all.
This answers the next question: does a 200 actually carry result links, or
is it a search form, a challenge page, or a zero-hit page? Those are
indistinguishable by status code and byte count alone.

Usage:
    python -m scripts.explore.dump_candidate <candidate-name> [--query "..."]
    python -m scripts.explore.dump_candidate <candidate-name> --links
"""

import argparse
import re
import sys
import urllib.parse

from scripts.explore.probe_search_alternatives import CANDIDATES, fetch

# Chrome, forum, and social hosts that appear on any results page as
# navigation rather than as a hit.
_CHROME = re.compile(
    r"(marginalia\.nu|mojeek\.com|searx|duckduckgo\.com|github\.com/searxng"
    r"|/settings|/about|/privacy|/preferences|javascript:|mailto:)",
    re.I,
)


def outbound_links(html: str) -> list[str]:
    """Absolute http(s) hrefs that are not site chrome, in document order."""
    seen, out = set(), []
    for href in re.findall(r'href=["\'](https?://[^"\']+)["\']', html):
        if _CHROME.search(href) or href in seen:
            continue
        seen.add(href)
        out.append(href)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidate", nargs="?", help=f"one of: {', '.join(CANDIDATES)}")
    parser.add_argument(
        "--query", default="Hungary property transfer duty non-resident buyer"
    )
    parser.add_argument(
        "--links", action="store_true", help="print outbound links only"
    )
    parser.add_argument("--bytes", type=int, default=3000, help="body prefix to print")
    parser.add_argument(
        "--url", default="", help="fetch an arbitrary URL instead of a named candidate"
    )
    args = parser.parse_args()

    if args.url:
        url = args.url
        args.candidate = args.candidate or "(--url)"
    elif args.candidate in CANDIDATES:
        url = CANDIDATES[args.candidate].format(
            q=urllib.parse.quote(args.query, safe="")
        )
    else:
        print(f"unknown: {args.candidate}", file=sys.stderr)
        raise SystemExit(2)
    status, ctype, body = fetch(url)
    text = body.decode("utf-8", errors="replace")
    print(f"# {args.candidate}  HTTP {status}  {ctype}  {len(body)} bytes")
    print(f"# {url}\n")

    if args.links:
        links = outbound_links(text)
        print(f"# {len(links)} non-chrome outbound links")
        for link in links[:40]:
            print(link)
        return
    print(text[: args.bytes])


if __name__ == "__main__":
    main()
