# Generated By: Claude Code (Claude Opus 5 (1M context))
# Copyright 2026 Naveen Malik
# Licensed under the Apache License, Version 2.0

"""Probe candidate search backends that do NOT depend on ddgs.

Why this exists: every ddgs backend is a scraper defended by anti-bot
measures, so the live set collapses without warning — four probes in one
session went 3/7, 1/7, 2/7, 2/7 alive, leaving one usable web engine. The
question this script answers is whether any search source can be reached
through the host-side fetch service instead, which needs no network-policy
entry and no TLS impersonation.

Each candidate is a plain GET whose response should be JSON or HTML we can
parse. Reported per candidate: the fetch service's HTTP status, the upstream
content type, body size, and a body prefix, so a dead end is distinguishable
from an anti-bot challenge page.

Usage:
    python -m scripts.explore.probe_search_alternatives
    python -m scripts.explore.probe_search_alternatives --query "..."
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

DEFAULT_SERVICE = "http://172.30.0.21:8090"
TIMEOUT_SECONDS = 45

# name -> URL template with {q} for the percent-encoded query.
CANDIDATES = {
    # Independent index, explicitly bot-friendly, no key on the public tier.
    "marginalia": "https://api.marginalia.nu/public/search/{q}",
    "marginalia-alt": "https://old-search.marginalia.nu/search?query={q}",
    # Independent crawler with a documented public API.
    "stract": "https://stract.com/beta/api/search?query={q}",
    # SearXNG metasearch. Most instances disable format=json; test a few.
    "searx-be": "https://searx.be/search?q={q}&format=json",
    "searx-priv": "https://priv.au/search?q={q}&format=json",
    "searx-tiekoetter": "https://searxng.site/search?q={q}&format=json",
    # Text-only DDG endpoint — cheaper to parse than the JS page, and the
    # question is whether it challenges a plain GET the way the main host does.
    "ddg-lite": "https://lite.duckduckgo.com/lite/?q={q}",
    "ddg-html": "https://html.duckduckgo.com/html/?q={q}",
    # Mojeek serves static HTML and publishes a crawler-friendly policy.
    "mojeek-html": "https://www.mojeek.com/search?q={q}",
    # Scholarly indexes: no key, no anti-bot, Tier 1 by construction.
    "openalex": "https://api.openalex.org/works?search={q}&per-page=5",
    "crossref": "https://api.crossref.org/works?query={q}&rows=5",
    # Wikipedia full-text search (not the 1-result opensearch ddgs uses).
    "wikipedia-srsearch": (
        "https://en.wikipedia.org/w/api.php?action=query&list=search"
        "&srsearch={q}&format=json&srlimit=5"
    ),
    # Second round: general-web JSON APIs that publish an unauthenticated
    # endpoint, plus more scholarly indexes.
    "qwant": (
        "https://api.qwant.com/v3/search/web?q={q}&count=10"
        "&locale=en_US&offset=0&device=desktop"
    ),
    "yep": (
        "https://api.yep.com/fs/2/search?client=web&gl=US&limit=20"
        "&no_correct=false&q={q}&safeSearch=off&type=web"
    ),
    "semanticscholar": (
        "https://api.semanticscholar.org/graph/v1/paper/search"
        "?query={q}&limit=5&fields=title,url,abstract,year"
    ),
    "pubmed": (
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        "?db=pubmed&term={q}&retmode=json&retmax=5"
    ),
    "searx-rhscz": "https://searx.rhscz.eu/search?q={q}&format=json",
    "searx-work": "https://search.inetol.net/search?q={q}&format=json",
    "marginalia-new": "https://search.marginalia.nu/search?query={q}",
}


def service_base() -> str:
    return os.environ.get("CITED_RESEARCH_FETCH_SERVICE", DEFAULT_SERVICE).rstrip("/")


def fetch(url: str) -> tuple[int, str, bytes]:
    """Fetch through the service. Returns (status, content_type, body)."""
    request_url = f"{service_base()}/fetch?url={urllib.parse.quote(url, safe='')}"
    try:
        with urllib.request.urlopen(request_url, timeout=TIMEOUT_SECONDS) as resp:
            return resp.status, resp.headers.get("Content-Type", ""), resp.read()
    except urllib.error.HTTPError as e:
        try:
            body = e.read()
        except Exception:
            body = b""
        return e.code, e.headers.get("Content-Type", "") if e.headers else "", body
    except (urllib.error.URLError, OSError) as e:
        return 0, "", str(e).encode()


def count_results(name: str, ctype: str, body: bytes) -> str:
    """Best-effort result count, so a 200 with zero results is not read as a win."""
    if "json" not in ctype.lower():
        return ""
    try:
        payload = json.loads(body)
    except ValueError:
        return "  (not parseable as JSON despite the content type)"
    for key in ("results", "webpages", "items", "message"):
        node = payload.get(key) if isinstance(payload, dict) else None
        if isinstance(node, list):
            return f"  results={len(node)}"
        if isinstance(node, dict) and isinstance(node.get("items"), list):
            return f"  results={len(node['items'])}"
    if isinstance(payload, dict) and isinstance(payload.get("query"), dict):
        hits = payload["query"].get("search")
        if isinstance(hits, list):
            return f"  results={len(hits)}"
    return "  (JSON parsed, no recognised results array)"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--query",
        default="Hungary property transfer duty non-resident buyer",
        help="query to send to every candidate",
    )
    parser.add_argument(
        "--only", default="", help="comma-separated subset of candidate names"
    )
    args = parser.parse_args()

    encoded = urllib.parse.quote(args.query, safe="")
    wanted = [n.strip() for n in args.only.split(",") if n.strip()] or list(CANDIDATES)
    unknown = [n for n in wanted if n not in CANDIDATES]
    if unknown:
        print(f"unknown candidate(s): {', '.join(unknown)}", file=sys.stderr)
        raise SystemExit(2)

    for name in wanted:
        url = CANDIDATES[name].format(q=encoded)
        status, ctype, body = fetch(url)
        prefix = body[:160].decode("utf-8", errors="replace").replace("\n", " ")
        print(
            f"{name:22} HTTP {status:<4} {ctype.split(';')[0]:<26} "
            f"{len(body):>8} bytes{count_results(name, ctype, body)}"
        )
        print(f"{'':22} {prefix}")


if __name__ == "__main__":
    main()
